#!/usr/bin/env python3
"""
Generate type_mappings.rs from Haxe standard library.

This script:
1. Creates a Haxe file that imports key std library modules
2. Runs haxe --xml to get type information
3. Parses the XML to find types where path != module.TypeName
4. Generates a Rust file with the expansion mapping

Usage:
    python3 gen_type_mappings.py [--haxe PATH] [--output PATH]
"""

import argparse
import os
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path


# Haxe source that imports key modules to include their types in the XML
HAXE_IMPORTS = """
// Auto-generated imports to get complete type coverage
import haxe.macro.Expr;
import haxe.macro.Type;
import haxe.rtti.CType;

class TypeCatalog {
    static function main() {
        // Force types to be included by referencing them
        var _b:Binop;
        var _u:Unop;
        var _t:haxe.macro.Type;
        var _c:haxe.rtti.CType;
    }
}
"""


def find_haxe() -> str:
    """Find the haxe compiler in PATH or common locations."""
    # Check PATH
    for path in os.environ.get("PATH", "").split(os.pathsep):
        haxe = os.path.join(path, "haxe")
        if os.path.isfile(haxe) and os.access(haxe, os.X_OK):
            return haxe

    # Check common locations
    common_paths = [
        "/home/bmd/haxe_heaps_gles/haxe/haxe",
        "/usr/local/bin/haxe",
        "/usr/bin/haxe",
    ]
    for path in common_paths:
        if os.path.isfile(path) and os.access(path, os.X_OK):
            return path

    raise RuntimeError("Could not find haxe compiler. Please specify with --haxe")


def generate_xml(haxe_path: str, output_xml: str) -> None:
    """Run haxe --xml to generate the type catalog."""
    with tempfile.TemporaryDirectory() as tmpdir:
        # Write the imports file
        haxe_file = os.path.join(tmpdir, "TypeCatalog.hx")
        with open(haxe_file, "w") as f:
            f.write(HAXE_IMPORTS)

        # Run haxe
        cmd = [
            haxe_path,
            "--xml", output_xml,
            "--main", "TypeCatalog",
            "--hl", os.path.join(tmpdir, "out.hl"),
            "-cp", tmpdir,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"Warning: haxe returned non-zero: {result.stderr}", file=sys.stderr)


def parse_xml(xml_path: str) -> list[tuple[str, str]]:
    """Parse the XML and find types that need expansion."""
    tree = ET.parse(xml_path)
    root = tree.getroot()

    expansions = []
    for elem in root:
        path = elem.get('path')
        module = elem.get('module')
        if not path or not module:
            continue

        # Skip types without package (Int, Bool, etc.)
        if '.' not in path:
            continue

        # Get the type name (last component)
        type_name = path.split('.')[-1]

        # Get the package from path (everything except last component)
        path_pkg = '.'.join(path.split('.')[:-1])

        # Check if path already includes module
        if path_pkg == module:
            continue

        # Get module package
        mod_pkg = '.'.join(module.split('.')[:-1])

        # Only expand if path package matches module package
        # (meaning the module name is missing from path)
        if path_pkg == mod_pkg:
            full_path = f"{module}.{type_name}"
            expansions.append((path, full_path))

    return sorted(expansions)


def generate_rust(expansions: list[tuple[str, str]], output_path: str) -> None:
    """Generate the Rust source file with the type mapping."""
    lines = [
        "//! Auto-generated type path expansions.",
        "//!",
        "//! Generated by scripts/gen_type_mappings.py from Haxe standard library.",
        "//! This maps short type paths (as stored in bytecode) to full module paths.",
        "",
        "/// Expand a short type path to its full module path.",
        "///",
        "/// Returns Some(expanded) if the path needs expansion, None otherwise.",
        "///",
        "/// # Examples",
        "/// ```",
        '/// assert_eq!(expand_module_path("haxe.macro.Binop"), Some("haxe.macro.Expr.Binop"));',
        '/// assert_eq!(expand_module_path("String"), None);',
        "/// ```",
        "pub fn expand_module_path(path: &str) -> Option<&'static str> {",
        "    match path {",
    ]

    for short, full in expansions:
        lines.append(f'        "{short}" => Some("{full}"),')

    lines.extend([
        "        _ => None,",
        "    }",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    #[test]",
        "    fn test_expand_macro_types() {",
        '        assert_eq!(expand_module_path("haxe.macro.Binop"), Some("haxe.macro.Expr.Binop"));',
        '        assert_eq!(expand_module_path("haxe.macro.Unop"), Some("haxe.macro.Expr.Unop"));',
        '        assert_eq!(expand_module_path("haxe.macro.ClassType"), Some("haxe.macro.Type.ClassType"));',
        "    }",
        "",
        "    #[test]",
        "    fn test_no_expansion_needed() {",
        '        assert_eq!(expand_module_path("String"), None);',
        '        assert_eq!(expand_module_path("Int"), None);',
        '        assert_eq!(expand_module_path("haxe.ds.StringMap"), None);',
        "    }",
        "}",
        "",
    ])

    with open(output_path, "w") as f:
        f.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description="Generate type_mappings.rs from Haxe std library")
    parser.add_argument("--haxe", help="Path to haxe compiler")
    parser.add_argument("--output", help="Output Rust file path")
    args = parser.parse_args()

    # Find paths
    script_dir = Path(__file__).parent
    decompiler_src = script_dir.parent / "src"

    haxe_path = args.haxe or find_haxe()
    output_path = args.output or str(decompiler_src / "type_mappings.rs")

    print(f"Using haxe: {haxe_path}")
    print(f"Output: {output_path}")

    # Generate XML in temp file
    with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
        xml_path = f.name

    try:
        print("Generating type catalog XML...")
        generate_xml(haxe_path, xml_path)

        print("Parsing XML...")
        expansions = parse_xml(xml_path)
        print(f"Found {len(expansions)} types to expand")

        print("Generating Rust file...")
        generate_rust(expansions, output_path)
        print(f"Generated {output_path}")

    finally:
        if os.path.exists(xml_path):
            os.unlink(xml_path)


if __name__ == "__main__":
    main()
