//! The decompiler used to get haxe sources back from the bytecode definitions.
//! More info on how everything works in the [wiki](https://github.com/Gui-Yom/hlbc/wiki/Decompilation).
//!
//! The decompiler takes bytecode elements as input and outputs [ast] structures that can be displayed.

use std::cell::RefCell;
use std::collections::{HashMap, HashSet};

// Thread-local set of functions currently being decompiled (to detect recursive closures)
thread_local! {
    static DECOMPILING_FUNCTIONS: RefCell<HashSet<usize>> = RefCell::new(HashSet::new());
}

/// Check if a function is currently being decompiled (for recursive closure detection)
pub fn is_currently_decompiling(findex: usize) -> bool {
    DECOMPILING_FUNCTIONS.with(|set| set.borrow().contains(&findex))
}

use ast::*;
use hlbc::opcodes::Opcode;
use hlbc::types::{Function, ObjProto, RefField, RefGlobal, RefString, Reg, Type, TypeObj};
use hlbc::Bytecode;
#[cfg(feature = "alt")]
mod alt;
/// A simple representation for the Haxe source code generated by the decompiler
pub mod ast;
/// Batch decompilation to files
#[cfg(feature = "batch")]
pub mod batch;
/// Functions to render the [ast] to a string
pub mod fmt;
/// Native function name lookup
pub mod natives;
/// Pass 1: CFG construction using petgraph
pub mod lifter;
/// Pass 2: Dominator computation and loop detection
pub mod analyzer;
/// Pass 3: SSA construction (φ-functions and variable versioning)
pub mod ssa;
/// Pass 4: Type propagation through SSA graph
pub mod type_prop;
/// Pass 5: Convert SSA-CFG to structured AST
pub mod structurer;
/// AST post-processing
mod post;
/// Closure pattern detection and analysis
pub mod closure_analysis;
/// Exception region analysis for try/catch structuring
pub mod exception_analysis;
/// Generic type parameter inference
pub mod generic_inference;
/// Type path expansions for shortened bytecode type names
pub mod type_mappings;

// Re-export ClosureAnalysis for convenience
pub use closure_analysis::ClosureAnalysis;
// Re-export ExceptionAnalysis for convenience
pub use exception_analysis::ExceptionAnalysis;

/// Map from (static_type_global, field_index) -> initialization Expr
/// Used to track static field initializers extracted from the entrypoint function.
pub type StaticInitMap = HashMap<(RefGlobal, RefField), Expr>;

/// Extract static field initializers from the entrypoint function.
///
/// Static fields are initialized in the entrypoint via SetField operations:
/// ```text
/// OInt      r12 = 10           # Load value into register
/// OGetGlobal r19 = G4          # Load static type ($Counter)
/// OSetField r19.F6 = r12       # Set MULTIPLIER field
/// ```
pub fn extract_static_initializers(code: &Bytecode) -> StaticInitMap {
    let mut result = HashMap::new();
    let entrypoint = code.entrypoint();

    // Track register values as we scan opcodes
    let mut reg_values: HashMap<Reg, Expr> = HashMap::new();
    // Track which register holds which global (for static type refs)
    let mut reg_globals: HashMap<Reg, RefGlobal> = HashMap::new();

    for op in entrypoint.ops.iter() {
        match op {
            // Track constant loads
            Opcode::Int { dst, ptr } => {
                reg_values.insert(*dst, Expr::Constant(Constant::Int(*ptr)));
            }
            Opcode::Float { dst, ptr } => {
                reg_values.insert(*dst, Expr::Constant(Constant::Float(*ptr)));
            }
            Opcode::Bool { dst, value } => {
                reg_values.insert(*dst, Expr::Constant(Constant::Bool(*value)));
            }
            Opcode::String { dst, ptr } => {
                reg_values.insert(*dst, Expr::Constant(Constant::String(*ptr)));
            }
            Opcode::Null { dst } => {
                reg_values.insert(*dst, Expr::Constant(Constant::Null));
            }

            // Track GetGlobal - remember which register holds which global
            Opcode::GetGlobal { dst, global } => {
                reg_globals.insert(*dst, *global);
                // Also check if this global is a string constant
                if let Some(expr) = global_to_expr(code, *global) {
                    reg_values.insert(*dst, expr);
                }
            }

            // SetField on a static type global -> record the initialization
            Opcode::SetField { obj, field, src } => {
                if let Some(&global) = reg_globals.get(obj) {
                    // Check if this global is a static type ($ClassName)
                    if is_static_type_global(code, global) {
                        if let Some(value) = reg_values.get(src).cloned() {
                            result.insert((global, *field), value);
                        }
                    }
                }
            }

            _ => {}
        }
    }
    result
}

/// Check if a global holds a static type (name starts with $).
/// Note: GetGlobal opcode uses 0-based global indexing directly into code.globals.
fn is_static_type_global(code: &Bytecode, global: RefGlobal) -> bool {
    if let Some(global_type) = code.globals.get(global.0) {
        match &code[*global_type] {
            Type::Obj(obj) | Type::Struct(obj) => {
                code[obj.name].starts_with('$')
            }
            _ => false,
        }
    } else {
        false
    }
}

/// Convert a global reference to an Expr if it represents a constant value.
/// Note: GetGlobal opcode uses 0-based global indexing directly into code.globals.
fn global_to_expr(code: &Bytecode, global: RefGlobal) -> Option<Expr> {
    // For string globals, look up the constant value
    let global_type = code.globals.get(global.0)?;
    // String type is index 13
    if global_type.0 == 13 {
        let const_idx = code.globals_initializers.get(&global)?;
        let constants = code.constants.as_ref()?;
        let def = constants.get(*const_idx)?;
        let string_idx = *def.fields.first()?;
        return Some(Expr::Constant(Constant::String(RefString(string_idx))));
    }
    None
}


/// Decompile a function to a list of [Statement]s using the multi-pass pipeline.
///
/// Pipeline: Bytecode → Lifter → CFG → Analyzer → SSA Builder → Type Prop → Structurer → AST
pub fn decompile_code(code: &Bytecode, f: &Function) -> Vec<Statement> {
    decompile_code_with_closures(code, f, None)
}

/// Decompile a function with closure analysis context.
///
/// When `closure_analysis` is provided, the decompiler can:
/// - Detect closure-creating functions and suppress internal enum machinery
/// - Identify captured variables and remap them to original names in inner functions
/// - Inline closure bodies at InstanceClosure sites
pub fn decompile_code_with_closures(
    code: &Bytecode,
    f: &Function,
    closure_analysis: Option<&ClosureAnalysis>,
) -> Vec<Statement> {
    decompile_code_with_options(code, f, closure_analysis, false)
}

/// Decompile a function with full options.
///
/// `is_this_bound_closure`: Set to true when decompiling an inline function from
/// an `InstanceClosure` opcode where reg0 is implicitly bound to `this`.
pub fn decompile_code_with_options(
    code: &Bytecode,
    f: &Function,
    closure_analysis: Option<&ClosureAnalysis>,
    is_this_bound_closure: bool,
) -> Vec<Statement> {
    use crate::lifter::Cfg;
    use crate::analyzer::CfgAnalysis;
    use crate::ssa::SsaCfg;
    use crate::type_prop::TypePropagator;
    use crate::structurer::{
        Structurer, PatternContext, reduce_to_region, LoweringContext, lower_region,
        simplify_statements,
    };

    let findex = f.findex.0;

    // Mark this function as currently being decompiled
    // (recursive closure detection is done in structurer before calling this)
    DECOMPILING_FUNCTIONS.with(|set| {
        set.borrow_mut().insert(findex);
    });

    // Pass 1: Build CFG
    let cfg = Cfg::build(f);

    // Pass 2: Analyze for loops and dominators
    let analysis = CfgAnalysis::analyze(&cfg);

    // Pass 3: Build SSA with φ-functions
    let ssa = SsaCfg::build(f, &cfg, &analysis);

    // Pass 4: Type propagation
    let propagator = TypePropagator::new(code, f, &cfg, &ssa);
    let type_info = propagator.propagate();

    // Pass 5: Structure into AST using the new iterative reducer
    // The reducer detects high-level patterns like for-in loops via SSA analysis
    let mut structurer = Structurer::new_with_options(
        code, f, &cfg, &analysis, &ssa, &type_info, closure_analysis, is_this_bound_closure
    );

    // Run preprocessing for pattern suppression
    structurer.detect_internal_function_calls();

    // Check if function has exception handling or string switches - use legacy path
    // String switch detection requires opcode-level pattern matching that the new
    // reducer path doesn't support yet.
    let has_exceptions = structurer.exception_analysis.has_exceptions();
    let has_string_switches = !structurer.string_switches.is_empty();
    let mut stmts = if has_exceptions || has_string_switches {
        // Legacy path handles Trap/EndTrap and string switch patterns correctly
        structurer.structure()
    } else {
        // New reducer path with for-in detection
        let pattern_ctx = PatternContext {
            code,
            func: f,
            ssa: &ssa,
            type_info: &type_info,
        };
        let region = reduce_to_region(&cfg, &analysis, Some(&pattern_ctx));

        // Lower the region tree to statements
        let mut lowering_ctx = LoweringContext::new(&mut structurer);
        let lowered_stmts = lower_region(&region, &mut lowering_ctx);

        // Extract needed data from structurer while it's still borrowed
        let current_class = lowering_ctx.structurer.get_current_class_name();
        let current_class_str = current_class.as_ref().map(|s| s.as_ref());

        // Prepend hoisted variable declarations (same as legacy structure())
        let mut result = Vec::new();
        for name in &lowering_ctx.structurer.hoisted_vars {
            let type_hint = if lowering_ctx.structurer.needs_dynamic_type.contains(name) {
                Some("Dynamic".into())
            } else if let Some(type_ref) = lowering_ctx.structurer.hoisted_var_types.get(name) {
                let ty = &code.types[type_ref.0];
                let type_str = crate::fmt::to_haxe_type_in_context(ty, code, current_class_str);
                if type_str == "Void" || type_str == "haxe.Exception" {
                    Some("Dynamic".into())
                } else {
                    Some(type_str)
                }
            } else {
                None
            };
            result.push(Statement::VarDecl { name: name.clone(), type_hint });
        }
        result.extend(lowered_stmts);

        simplify_statements(result)
    };

    // Pass 6: Post-processing transformations
    post::reconstruct_array_literals(code, &mut stmts);

    // Pass 6b: Restore string concatenation from __add__ calls
    post::apply_string_concat(code, &mut stmts);

    // Pass 7: Iterative optimization loop
    // Multiple passes can enable each other (e.g., inverting empty ifs can expose early return patterns)
    // Note: condense_ternary_returns has been migrated to structurer.rs (try_condense_ternary_return)
    const MAX_OPT_ITERATIONS: usize = 10;
    for _ in 0..MAX_OPT_ITERATIONS {
        let mut changed = false;

        // Invert empty if bodies: if (c) {} else { body } → if (!c) { body }
        // DISABLED: Moving this logic into the structurer where we have branch polarity info.
        // if post::invert_empty_ifs(&mut stmts) {
        //     changed = true;
        // }

        // Flatten early returns: if (x) { return; } else { body } → if (x) { return; } body
        if post::flatten_early_returns(&mut stmts) {
            changed = true;
        }

        if !changed {
            break;
        }
    }

    // Pass 8: Inline single-use variables to reduce verbosity
    post::inline_single_use_vars(&mut stmts);

    // Pass 9: Merge forward declarations with first assignments
    // DISABLED: This pass incorrectly merges hoisted VarDecls with assignments that
    // are at the wrong scope level (e.g., assignments that should be inside if blocks
    // but ended up at top level due to region structuring issues). The hoisting in
    // the structurer works correctly - this pass undoes it incorrectly.
    // TODO: Move this logic into the structurer where scope information is available.
    // post::merge_declarations(&mut stmts);

    // Pass 10: Inline constants that are immediately returned
    post::inline_constant_returns(&mut stmts);

    // Note: remove_unused_var_decls is no longer needed - the structurer now
    // uses SSA info to only emit VarDecls for variables that actually have
    // assignments emitted, avoiding orphaned declarations.

    // Pass 11: Collapse verbose trace() patterns into simple trace(message) calls
    // This runs after inlining so the pattern is simplified
    post::collapse_trace_calls(&mut stmts);

    // Pass 13: Boolean simplification - fold nested ifs into && and ||
    // if (a) { if (b) { X } } → if (a && b) { X }
    post::simplify_boolean_conditions(&mut stmts);

    // Pass 14: For-in loop detection - convert while counter patterns to for-in
    // var i = 0; while (i < n) { body; i++; } → for (i in 0...n) { body }
    post::detect_for_in_loops(&mut stmts);

    // Clean up: remove this function from the "currently decompiling" set
    DECOMPILING_FUNCTIONS.with(|set| {
        set.borrow_mut().remove(&findex);
    });

    stmts
}

/// Decompile a function out of context, returning a Method.
pub fn decompile_function(code: &Bytecode, f: &Function) -> Method {
    // Detect if this is an instance method by checking if the first parameter
    // is an object type (which would be `this`)
    let is_instance_method = f.ty(code).args.first()
        .and_then(|arg| code.types.get(arg.0))
        .map(|ty| matches!(ty, hlbc::types::Type::Obj(_) | hlbc::types::Type::Struct(_)))
        .unwrap_or(false);

    Method {
        fun: f.findex,
        static_: !is_instance_method,
        dynamic: false,
        override_: false,
        statements: decompile_code(code, f),
    }
}

/// Decompile a function with closure analysis, returning a Method.
pub fn decompile_function_with_closures(
    code: &Bytecode,
    f: &Function,
    closure_analysis: Option<&ClosureAnalysis>,
) -> Method {
    // Detect if this is an instance method by checking if the first parameter
    // is an object type (which would be `this`)
    let is_instance_method = f.ty(code).args.first()
        .and_then(|arg| code.types.get(arg.0))
        .map(|ty| matches!(ty, hlbc::types::Type::Obj(_) | hlbc::types::Type::Struct(_)))
        .unwrap_or(false);

    Method {
        fun: f.findex,
        static_: !is_instance_method,
        dynamic: false,
        override_: false,
        statements: decompile_code_with_closures(code, f, closure_analysis),
    }
}


/// Decompile a class with its static and instance fields and methods.
pub fn decompile_class(code: &Bytecode, obj: &TypeObj, static_inits: &StaticInitMap) -> Class {
    decompile_class_with_closures(code, obj, static_inits, None)
}

/// Decompile a class with closure analysis context.
pub fn decompile_class_with_closures(
    code: &Bytecode,
    obj: &TypeObj,
    static_inits: &StaticInitMap,
    closure_analysis: Option<&ClosureAnalysis>,
) -> Class {
    let static_type = obj.get_static_type(code);

    let mut fields = Vec::new();
    for (i, f) in obj.own_fields.iter().enumerate() {
        if obj
            .bindings
            .contains_key(&RefField(i + obj.fields.len() - obj.own_fields.len()))
        {
            continue;
        }
        // Skip fields with empty names (interface implementation cache fields)
        // Note: hlbc converts empty strings to "<none>"
        let field_name = f.name(code);
        if field_name.is_empty() || field_name.as_ref() == "<none>" {
            continue;
        }
        fields.push(ClassField {
            name: field_name.to_owned(),
            static_: false,
            ty: f.t,
            initializer: None, // Instance fields don't have initializers from entrypoint
            inferred_generics: None,
        });
    }
    if let Some(ty) = static_type {
        // Convert from 1-based TypeObj.global to 0-based opcode global indexing
        let static_global = if obj.global.0 > 0 {
            RefGlobal(obj.global.0 - 1)
        } else {
            obj.global
        };

        for (i, f) in ty.own_fields.iter().enumerate() {
            let field_idx = RefField(i + ty.fields.len() - ty.own_fields.len());
            if ty.bindings.contains_key(&field_idx) {
                continue;
            }
            // Skip fields with empty names (interface implementation cache fields)
            // Note: hlbc converts empty strings to "<none>"
            let field_name = f.name(code);
            if field_name.is_empty() || field_name.as_ref() == "<none>" {
                continue;
            }
            // Look up initializer from entrypoint analysis
            let initializer = static_inits.get(&(static_global, field_idx)).cloned();
            fields.push(ClassField {
                name: field_name.to_owned(),
                static_: true,
                ty: f.t,
                initializer,
                inferred_generics: None,
            });
        }
    }

    // Helper to check if a proto overrides a parent method
    let is_override = |proto: &ObjProto| -> bool {
        if proto.pindex < 0 {
            return false;
        }
        // Check if parent class has a proto with the same pindex
        if let Some(parent_type) = obj.super_ {
            if let Some(parent_obj) = parent_type.as_obj(code) {
                // Search up the inheritance chain
                let mut current = Some(parent_obj);
                while let Some(curr) = current {
                    for parent_proto in &curr.protos {
                        if parent_proto.pindex >= 0 && parent_proto.pindex == proto.pindex {
                            return true;
                        }
                    }
                    current = curr.super_.and_then(|t| t.as_obj(code));
                }
            }
        }
        false
    };

    let mut methods = Vec::new();
    for fun in obj.bindings.values() {
        // Skip native functions - can't decompile them
        if let Some(func) = fun.as_fn(code) {
            // Skip internal HashLink functions that access private fields
            let name = func.name(code);
            if name.starts_with("__") && !name.starts_with("__constructor__") {
                continue;
            }
            methods.push(Method {
                fun: *fun,
                static_: false,
                dynamic: true,
                override_: false, // Bindings don't override
                statements: decompile_code_with_closures(code, func, closure_analysis),
            })
        }
    }
    if let Some(ty) = static_type {
        for fun in ty.bindings.values() {
            // Skip native functions - can't decompile them
            if let Some(func) = fun.as_fn(code) {
                // Skip internal HashLink functions that access private fields
                let name = func.name(code);
                if name.starts_with("__") && !name.starts_with("__constructor__") {
                    continue;
                }
                methods.push(Method {
                    fun: *fun,
                    static_: true,
                    dynamic: false,
                    override_: false, // Static methods don't override
                    statements: decompile_code_with_closures(code, func, closure_analysis),
                })
            }
        }
    }
    for proto in &obj.protos {
        // Skip native functions - can't decompile them
        if let Some(func) = proto.findex.as_fn(code) {
            // Skip internal HashLink functions that access private fields
            // These are auto-generated and can't be recompiled correctly
            let name = func.name(code);
            if name.starts_with("__") && !name.starts_with("__constructor__") {
                continue;
            }
            methods.push(Method {
                fun: proto.findex,
                static_: false,
                dynamic: false,
                override_: is_override(proto),
                statements: decompile_code_with_closures(code, func, closure_analysis),
            })
        }
    }

    // Run generic type parameter inference
    // Collect method statement references for analysis
    let method_stmts: Vec<Vec<Statement>> = methods.iter()
        .map(|m| m.statements.clone())
        .collect();
    generic_inference::infer_generic_params_for_class(&mut fields, &method_stmts, code);

    Class {
        name: obj.name(code).to_owned(),
        parent: obj
            .super_
            .and_then(|ty| ty.as_obj(code))
            .map(|ty| ty.name(code).to_owned()),
        fields,
        methods,
    }
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::hint::black_box;

    use hlbc::Bytecode;

    use crate::{decompile_class, decompile_code, decompile_function, extract_static_initializers};

    #[test]
    fn decomp_code_all() {
        for entry in fs::read_dir("../../data").unwrap() {
            let path = entry.unwrap().path();
            if let Some(ext) = path.extension() {
                if ext == "hl" {
                    let code = Bytecode::from_file(&path).unwrap();
                    for f in &code.functions {
                        black_box(decompile_code(&code, f));
                    }
                }
            }
        }
    }

    #[test]
    fn decomp_fn_all() {
        for entry in fs::read_dir("../../data").unwrap() {
            let path = entry.unwrap().path();
            if let Some(ext) = path.extension() {
                if ext == "hl" {
                    let code = Bytecode::from_file(&path).unwrap();
                    for f in &code.functions {
                        black_box(decompile_function(&code, f));
                    }
                }
            }
        }
    }

    #[test]
    fn decomp_class_all() {
        for entry in fs::read_dir("../../data").unwrap() {
            let path = entry.unwrap().path();
            if let Some(ext) = path.extension() {
                if ext == "hl" {
                    let code = Bytecode::from_file(&path).unwrap();
                    let static_inits = extract_static_initializers(&code);
                    for t in code.types.iter().filter_map(|t| t.get_type_obj()) {
                        black_box(decompile_class(&code, t, &static_inits));
                    }
                }
            }
        }
    }

    #[test]
    #[ignore] // Requires local game files
    fn decomp_northgard() {
        let code = Bytecode::from_file("E:\\Games\\Northgard\\hlboot.dat").unwrap();
        let static_inits = extract_static_initializers(&code);
        for f in &code.functions {
            black_box(decompile_code(&code, f));
        }
        for t in code.types.iter().filter_map(|t| t.get_type_obj()) {
            black_box(decompile_class(&code, t, &static_inits));
        }
        for f in &code.functions {
            black_box(decompile_function(&code, f));
        }
    }

    #[test]
    #[ignore] // Requires local game files
    fn decomp_wartales() {
        let code = Bytecode::from_file("E:\\Games\\Wartales\\hlboot.dat").unwrap();
        let static_inits = extract_static_initializers(&code);
        for f in &code.functions {
            black_box(decompile_code(&code, f));
        }
        for t in code.types.iter().filter_map(|t| t.get_type_obj()) {
            black_box(decompile_class(&code, t, &static_inits));
        }
        for f in &code.functions {
            black_box(decompile_function(&code, f));
        }
    }
}
