//! The decompiler used to get haxe sources back from the bytecode definitions.
//! More info on how everything works in the [wiki](https://github.com/Gui-Yom/hlbc/wiki/Decompilation).
//!
//! The decompiler takes bytecode elements as input and outputs [ast] structures that can be displayed.

use std::collections::{HashMap, HashSet};

use ast::*;
use hlbc::fmt::EnhancedFmt;
use hlbc::opcodes::Opcode;
use hlbc::types::{Function, RefField, RefFun, RefString, RefType, Reg, Type, TypeObj};
use hlbc::{Bytecode, Resolve, Str};
use scopes::*;

#[cfg(feature = "alt")]
mod alt;
/// A simple representation for the Haxe source code generated by the decompiler
pub mod ast;
/// Batch decompilation to files
#[cfg(feature = "batch")]
pub mod batch;
/// Functions to render the [ast] to a string
pub mod fmt;
/// Native function name lookup
pub mod natives;
/// Liveness analysis for accurate variable naming
mod liveness;
/// AST post-processing
mod post;
/// Scope handling structures
mod scopes;

/// Detect loop counter registers by looking ahead from a Label to find Incr ops.
/// Returns a set of registers that are incremented within the loop body.
fn detect_loop_counters(ops: &[Opcode], label_pos: usize) -> HashSet<Reg> {
    let mut counters = HashSet::new();

    // Find the backward JAlways that jumps back to this label
    for j in (label_pos + 1)..ops.len() {
        if let Opcode::JAlways { offset } = &ops[j] {
            let target = (j as i32 + 1 + *offset) as usize;
            if target == label_pos {
                // Found the loop end - scan for Incr ops within the loop body
                for k in label_pos..=j {
                    if let Opcode::Incr { dst } = &ops[k] {
                        counters.insert(*dst);
                    }
                }
                break;
            }
        }
    }
    counters
}

/// Detect variables that need hoisting - they have a debug name that first appears
/// inside the scope but the register is used after the scope ends.
///
/// This handles cases where a register is initialized before the loop but the
/// debug name (variable name) first appears in an assignment inside the loop.
fn detect_hoisting_needed(
    ops: &[Opcode],
    scope_start: usize,
    scope_end: usize,
    f: &hlbc::types::Function,
    code: &hlbc::Bytecode,
) -> Vec<(Reg, Option<Str>)> {
    use liveness::{get_defs, get_uses};

    let mut needs_hoisting = Vec::new();

    // Find debug names that appear BEFORE the scope
    let mut names_before_scope: HashSet<Str> = HashSet::new();
    for i in 0..scope_start {
        if let Some(name) = f.var_name(code, i) {
            names_before_scope.insert(name);
        }
    }

    // Find debug names that FIRST appear inside the scope, with their registers
    let mut names_first_in_scope: HashMap<Str, Reg> = HashMap::new();
    for i in scope_start..=scope_end {
        if let Some(name) = f.var_name(code, i) {
            // Only if this name wasn't seen before the scope
            if !names_before_scope.contains(&name) && !names_first_in_scope.contains_key(&name) {
                // Find the register this name is associated with
                for reg in get_defs(&ops[i]) {
                    names_first_in_scope.insert(name.clone(), reg);
                    break;
                }
            }
        }
    }

    // Check which of those names' registers are used after the scope
    let mut used_after: HashSet<Reg> = HashSet::new();
    for i in (scope_end + 1)..ops.len() {
        for reg in get_uses(&ops[i]) {
            used_after.insert(reg);
        }
    }

    // If a name's register is used after the scope, it needs hoisting
    for (name, reg) in names_first_in_scope {
        if used_after.contains(&reg) {
            needs_hoisting.push((reg, Some(name)));
        }
    }

    needs_hoisting
}

/// Pre-scan the entire function to find ALL loop counter registers.
/// This is called before processing any opcodes so that Int instructions
/// that initialize loop counters can emit variable declarations.
fn prescan_all_loop_counters(ops: &[Opcode]) -> HashSet<Reg> {
    let mut all_counters = HashSet::new();

    // Find all Labels that are loop targets (have backward JAlways)
    for (i, op) in ops.iter().enumerate() {
        if matches!(op, Opcode::Label) {
            // Check if this Label is a loop target
            let is_loop_target = ops.iter().enumerate().skip(i + 1).any(|(j, op)| {
                matches!(op, Opcode::JAlways { offset } if (j as i32 + *offset + 1) as usize == i)
            });
            if is_loop_target {
                // Found a loop - collect its counters
                let counters = detect_loop_counters(ops, i);
                all_counters.extend(counters);
            }
        }
    }
    all_counters
}

enum ExprCtx {
    Constructor {
        reg: Reg,
        pos: usize,
    },
    Anonymous {
        reg: Reg, // Which register holds the anonymous object
        pos: usize,
        fields: HashMap<RefField, Expr>,
        remaining: usize,
    },
}

struct DecompilerState<'c> {
    // Scope stack, holds the statements
    scopes: Scopes,
    // Expression values for each registers
    reg_state: HashMap<Reg, Expr>,
    // For parsing statements made of multiple instructions like constructor calls and anonymous structures
    // TODO move this to another pass on the generated ast
    expr_ctx: Vec<ExprCtx>,
    // Variable names we already declared, mapped to the register that owns them.
    // This prevents name collisions when debug info gives the same name to different registers.
    name_to_reg: HashMap<Str, Reg>,
    // Counter for synthetic variable names
    synthetic_var_counter: u32,
    f: &'c Function,
    code: &'c Bytecode,
    /// Info from a just-closed Try scope, waiting for the JAlways that skips the catch
    /// Format: (catch_start_addr, exc_register)
    pending_try_info: Option<(usize, Reg)>,
    /// Pending catch blocks waiting to be opened
    /// Format: (catch_start_addr, exc_register, catch_length, try_stmts)
    pending_catches: Vec<(usize, Reg, i32, Vec<Statement>)>,
    /// Saved register states for if/else scopes.
    /// When entering an If scope, we save the current reg_state so that register
    /// modifications inside the if don't affect code after the if closes.
    saved_reg_states: Vec<HashMap<Reg, Expr>>,
    /// Track registers set to null within each if/else scope depth.
    /// Only these registers are restored on scope close (to prevent null.array patterns).
    /// Registers set to non-null values (like constructors) are NOT restored,
    /// allowing them to persist after the scope.
    set_to_null_in_scope: Vec<HashSet<Reg>>,
    /// Saved register states for switch statements.
    /// Each switch saves the state before it starts, and restores when entering each case.
    /// This prevents register values from one case bleeding into another.
    switch_saved_states: Vec<HashMap<Reg, Expr>>,
    /// Registers that hold EnumIndex results, mapped to the source enum value register.
    /// Used to reconstruct enum pattern matching in switches.
    enum_index_sources: HashMap<Reg, Reg>,
    /// Stack of loop counter registers (for nested loops).
    /// When we detect a loop (Label with backward JAlways), we look ahead to find Incr ops
    /// and treat those registers as variables from the start, so loop conditions work correctly.
    loop_counters: Vec<HashSet<Reg>>,
    /// All loop counter registers in the function, pre-scanned at start.
    /// Used to handle Int opcodes that initialize loop counters BEFORE the Label.
    all_loop_counters: HashSet<Reg>,
    /// Live range analysis for accurate variable naming across control flow.
    live_ranges: liveness::LiveRangeMap,
    /// Maps live range ID -> variable name (assigned on first def).
    range_to_name: HashMap<usize, Str>,
}

impl<'c> DecompilerState<'c> {
    fn new(code: &'c Bytecode, f: &'c Function) -> DecompilerState<'c> {
        let scopes = Scopes::new();
        let mut reg_state = HashMap::with_capacity(f.regs.len());
        let expr_ctx = Vec::new();
        let mut name_to_reg = HashMap::new();

        let mut start = 0;
        // First argument / First register is 'this'
        if f.is_method() || code.get(f.name) == "__constructor__" {
            reg_state.insert(Reg(0), cst_this());
            start = 1;
        }

        // Initialize register state with the function arguments
        let mut param_counter = 0u32;
        for i in start..f.ty(code).args.len() {
            let name = f.arg_name(code, i - start).or_else(|| {
                param_counter += 1;
                Some(format!("arg{}", param_counter - 1).into())
            });
            let reg = Reg(i as u32);
            reg_state.insert(reg, Expr::Variable(reg, name.clone()));
            if let Some(name) = name {
                name_to_reg.insert(name, reg);
            }
        }

        // Pre-scan all loop counters so we can handle Int opcodes before the Label
        let all_loop_counters = prescan_all_loop_counters(&f.ops);

        // Compute live ranges for accurate variable naming across control flow
        // Use CFG-based analysis to properly handle branches that merge
        let cfg = liveness::CFG::build(&f.ops);
        let liveness_info = liveness::compute_liveness(&cfg);
        let live_ranges = liveness::ranges::extract_live_ranges(&cfg, &liveness_info, f.regs.len());

        Self {
            scopes,
            reg_state,
            expr_ctx,
            name_to_reg,
            synthetic_var_counter: 0,
            f,
            code,
            pending_try_info: None,
            pending_catches: Vec::new(),
            saved_reg_states: Vec::new(),
            set_to_null_in_scope: Vec::new(),
            switch_saved_states: Vec::new(),
            enum_index_sources: HashMap::new(),
            loop_counters: Vec::new(),
            all_loop_counters,
            live_ranges,
            range_to_name: HashMap::new(),
        }
    }

    /// Check if a register is a loop counter in any active loop scope
    fn is_loop_counter(&self, reg: Reg) -> bool {
        self.loop_counters.iter().any(|counters| counters.contains(&reg))
    }

    /// Generate a variable name for a register
    fn var_name(&mut self, reg: Reg) -> Str {
        let name: Str = format!("v{}", self.synthetic_var_counter).into();
        self.synthetic_var_counter += 1;
        self.name_to_reg.insert(name.clone(), reg);
        name
    }

    /// Get or create a variable name for a definition at a specific opcode index.
    /// Uses live range analysis to ensure consistent naming across control flow.
    fn var_name_for_def(&mut self, reg: Reg, op_index: usize, debug_name: Option<Str>) -> Str {
        if let Some(range_id) = self.live_ranges.get_range_id(reg, op_index) {
            // Check if we have an existing name for this live range
            if let Some(cached_name) = self.range_to_name.get(&range_id).cloned() {
                // If debug name is provided and differs from cached name,
                // the register is being reused for a different logical variable.
                // Respect the debug name in this case.
                if let Some(ref dn) = debug_name {
                    if *dn != cached_name {
                        // Different debug name - update the mapping
                        self.range_to_name.insert(range_id, dn.clone());
                        self.name_to_reg.insert(dn.clone(), reg);
                        return dn.clone();
                    }
                }
                return cached_name;
            }

            // Create new name - prefer debug name if available
            let name = debug_name.unwrap_or_else(|| {
                let n: Str = format!("v{}", self.synthetic_var_counter).into();
                self.synthetic_var_counter += 1;
                n
            });

            self.range_to_name.insert(range_id, name.clone());
            self.name_to_reg.insert(name.clone(), reg);
            name
        } else {
            // Fallback if no live range info
            let name = debug_name.unwrap_or_else(|| self.var_name(reg));
            // Ensure name is registered even in fallback path
            self.name_to_reg.entry(name.clone()).or_insert(reg);
            name
        }
    }

    /// Check if we're at a catch block start and open the catch scope
    fn check_catch_start(&mut self, i: usize) {
        if let Some(idx) = self.pending_catches.iter().position(|(start, _, _, _)| *start == i) {
            let (_, exc, len, try_stmts) = self.pending_catches.remove(idx);

            // Give the exception register an expression
            self.reg_state.insert(exc, Expr::Ident("e".into()));

            // Push catch scope with try_stmts
            self.scopes.push_catch(exc, len, try_stmts);
        }
    }

    fn push_stmt(&mut self, stmt: Statement) {
        self.scopes.push_stmt(stmt);
    }

    // Update the register state and create a statement depending on inline rules
    fn push_expr(&mut self, i: usize, dst: Reg, expr: Expr) {
        let name = self.f.var_name(self.code, i);
        // Track registers set to null in current scope (for selective restoration).
        // Only null assignments are tracked - constructors and other values persist after scope.
        if let Some(set_to_null) = self.set_to_null_in_scope.last_mut() {
            if matches!(&expr, Expr::Constant(Constant::Null)) {
                set_to_null.insert(dst);
            }
        }

        // Inside a conditional scope, if we're overwriting a register with a different
        // expression type (especially Null), we need to be careful about register reuse.
        // If the register previously had a non-trivial expression, create a synthetic
        // variable to prevent stale expression propagation.
        let force_variable = if !self.set_to_null_in_scope.is_empty() {
            // Check if this register had a meaningful expression before
            if let Some(prev_expr) = self.reg_state.get(&dst) {
                // If setting to null and previous was anything non-null, force variable
                // This handles all cases where register is reused across branches
                let is_null_prev = matches!(prev_expr, Expr::Constant(Constant::Null));
                matches!(&expr, Expr::Constant(Constant::Null)) && !is_null_prev
            } else {
                false
            }
        } else {
            false
        };

        // Inline check
        if name.is_none() && !force_variable {
            self.reg_state.insert(dst, expr);
        } else {
            // Check if this is a new declaration BEFORE calling var_name_for_def
            // (since var_name_for_def inserts into range_to_name)
            let is_new_range = if let Some(range_id) = self.live_ranges.get_range_id(dst, i) {
                !self.range_to_name.contains_key(&range_id)
            } else {
                // No live range info - check if we have a name registered for this register
                !self.name_to_reg.values().any(|&r| r == dst)
            };

            // Check if the name was already declared BEFORE calling var_name_for_def
            // (since var_name_for_def will add the name to name_to_reg).
            // This prevents parameter shadowing and redeclarations across branches.
            let name_already_declared = if let Some(ref n) = name {
                // Debug name provided - check if already declared
                self.name_to_reg.contains_key(n)
            } else if let Some(range_id) = self.live_ranges.get_range_id(dst, i) {
                // No debug name - check if this range already has a name
                self.range_to_name.contains_key(&range_id)
            } else {
                // Fallback - check if any name maps to this register
                self.name_to_reg.values().any(|&r| r == dst)
            };

            // Check if debug name differs from cached range name (register reuse for new variable)
            let is_new_variable = if let Some(ref n) = name {
                if let Some(range_id) = self.live_ranges.get_range_id(dst, i) {
                    if let Some(cached) = self.range_to_name.get(&range_id) {
                        n != cached  // Different name = new logical variable
                    } else {
                        false
                    }
                } else {
                    false
                }
            } else {
                false
            };

            // Create a variable using liveness-aware naming.
            // This ensures consistent names across control flow (e.g., if-else branches).
            let var_name = self.var_name_for_def(dst, i, name.clone());

            // A name is a new declaration if:
            // 1. It's a new live range AND the name wasn't already declared, OR
            // 2. It's a new logical variable (debug name differs from cached range name)
            let is_declaration = (is_new_range && !name_already_declared) || (is_new_variable && !name_already_declared);

            self.reg_state
                .insert(dst, Expr::Variable(dst, Some(var_name.clone())));

            self.push_stmt(Statement::Assign {
                declaration: is_declaration,
                variable: Expr::Variable(dst, Some(var_name)),
                assign: expr,
            });
        }
    }

    // Get the expr for a register
    fn expr(&self, reg: Reg) -> Expr {
        self.reg_state
            .get(&reg)
            .cloned()
            .unwrap_or_else(|| Expr::Unknown("missing expr".to_owned()))
    }

    /// Get expression for a register at a specific opcode index with correct variable name.
    /// Uses live range analysis to ensure we return the right variable name for this use site.
    fn expr_at(&self, reg: Reg, op_index: usize) -> Expr {
        let base = self.reg_state
            .get(&reg)
            .cloned()
            .unwrap_or_else(|| Expr::Unknown("missing expr".to_owned()));

        // If it's a variable, verify/fix the name based on liveness
        if let Expr::Variable(r, _) = &base {
            if *r == reg {
                // Try to find a name for this specific range
                if let Some(range_id) = self.live_ranges.get_range_id(reg, op_index) {
                    if let Some(name) = self.range_to_name.get(&range_id) {
                        return Expr::Variable(reg, Some(name.clone()));
                    }
                }
                // Fallback: If no name for this range, look for ANY range of this register
                // that has a name. This handles the case where multiple defs in different
                // branches should share the same variable name.
                for (rid, name) in &self.range_to_name {
                    if let Some(range) = self.live_ranges.ranges.get(*rid) {
                        if range.reg == reg {
                            return Expr::Variable(reg, Some(name.clone()));
                        }
                    }
                }
            }
        }
        base
    }

    /// Expands the expression of many registers
    fn args_expr(&self, args: &[Reg]) -> Vec<Expr> {
        args.iter().map(|&r| self.expr(r)).collect()
    }

    /// Expands expressions with correct variable names at a specific opcode index.
    fn args_expr_at(&self, args: &[Reg], op_index: usize) -> Vec<Expr> {
        args.iter().map(|&r| self.expr_at(r, op_index)).collect()
    }

    /// Ensure a register has a named variable, materializing it if needed.
    /// This is used for operations like Incr/Decr that need to reference a variable.
    /// Returns the variable expression.
    fn ensure_variable(&mut self, reg: Reg) -> Expr {
        let current_expr = self.expr(reg);

        // If it's already a variable, just return it
        if matches!(&current_expr, Expr::Variable(_, _)) {
            return current_expr;
        }

        // Need to materialize: create a synthetic variable name
        let var_name: Str = format!("v{}", self.synthetic_var_counter).into();
        self.synthetic_var_counter += 1;

        let var_expr = Expr::Variable(reg, Some(var_name.clone()));

        // Emit the variable declaration with the current expression
        let declaration = !self.name_to_reg.contains_key(&var_name);
        self.name_to_reg.insert(var_name.clone(), reg);
        self.push_stmt(Statement::Assign {
            declaration,
            variable: var_expr.clone(),
            assign: current_expr,
        });

        // Update the register state to point to the variable
        self.reg_state.insert(reg, var_expr.clone());

        var_expr
    }

    /// Check if `parent` is in the inheritance chain of `child`
    fn is_parent_class(&self, parent: RefType, child: RefType) -> bool {
        let mut current = child;
        while let Some(obj) = current.as_obj(self.code) {
            if let Some(super_) = obj.super_ {
                if super_ == parent {
                    return true;
                }
                current = super_;
            } else {
                break;
            }
        }
        false
    }

    /// Push a call to a function, which might be a constructor call.
    fn push_call(&mut self, i: usize, dst: Reg, fun: RefFun, args: &[Reg]) {
        // Check if this is a constructor call (first arg matches pending constructor reg)
        if let Some(&ExprCtx::Constructor { reg, pos }) = self.expr_ctx.last() {
            if args.first() == Some(&reg) {
                self.push_expr(
                    pos,
                    reg,
                    Expr::Constructor(ConstructorCall::new(
                        self.f.regtype(reg),
                        self.args_expr(&args[1..]),
                    )),
                );
                self.expr_ctx.pop();
                // If dst is different from reg, also store the call result there
                if dst != reg {
                    self.push_stmt(comment(fun.display::<EnhancedFmt>(self.code).to_string()));
                    self.push_expr(i, dst, call_fun(fun, self.args_expr(args)));
                }
                return;
            }
            // Not a constructor call - fall through to normal handling
        }

        // Normal function call handling
        {
            // Check if this is an internal conversion function that should be inlined
            // (itos/ftos/dtos are only used as intermediate values for __alloc__)
            let fun_name = fun.name(self.code);
            let should_inline = fun_name == "itos" || fun_name == "ftos" || fun_name == "dtos";

            // Only emit comment for non-inlined calls
            if !should_inline {
                self.push_stmt(comment(fun.display::<EnhancedFmt>(self.code).to_string()));
            }
            let call = if let Some((func, true)) =
                fun.as_fn(self.code).map(|func| (func, func.is_method()))
            {
                // Check if this is a super call: calling a parent class method with 'this'
                let is_super_call = args.first() == Some(&Reg(0)) && // First arg is 'this'
                    self.f.parent.is_some() && func.parent.is_some() && // Both are methods
                    self.f.parent != func.parent && // Different classes
                    self.is_parent_class(func.parent.unwrap(), self.f.parent.unwrap());

                let receiver = if is_super_call {
                    Expr::Ident("super".into())
                } else {
                    self.expr(args[0])
                };

                call(
                    Expr::Field(Box::new(receiver), func.name(self.code)),
                    self.args_expr(&args[1..]),
                )
            } else {
                call_fun(fun, self.args_expr(args))
            };
            let ret_type = fun.ty(self.code).ret;
            let is_void = ret_type.is_void();
            if is_void {
                self.push_stmt(stmt(call));
            } else if should_inline {
                // Inline conversion functions - they will be combined with __alloc__ in post-processing
                self.reg_state.insert(dst, call);
            } else {
                // For function calls, always materialize as a variable since:
                // 1. They often have side effects
                // 2. Results are typically stored in named variables in source code
                // 3. Inlining them on every use produces confusing output
                let name = self.f.var_name(self.code, i);
                if name.is_some() {
                    // Debug info available - use the original name
                    self.push_expr(i, dst, call);
                } else {
                    // No debug name - check if saved_reg_states has a variable for this register.
                    // This handles if/else branches that both assign to the same register.
                    let existing_var_name = self.saved_reg_states.last().and_then(|saved| {
                        if let Some(Expr::Variable(_, Some(name))) = saved.get(&dst) {
                            Some(name.clone())
                        } else {
                            None
                        }
                    });

                    let var_name: Str = existing_var_name.unwrap_or_else(|| {
                        let name = format!("v{}", self.synthetic_var_counter).into();
                        self.synthetic_var_counter += 1;
                        name
                    });
                    let var_expr = Expr::Variable(dst, Some(var_name.clone()));

                    let declaration = !self.name_to_reg.contains_key(&var_name);
                    self.name_to_reg.insert(var_name.clone(), dst);
                    self.push_stmt(Statement::Assign {
                        declaration,
                        variable: var_expr.clone(),
                        assign: call,
                    });
                    self.reg_state.insert(dst, var_expr);
                }
            }
        }
    }

    /// Process a jmp instruction, might be the exit condition of a loop or an if
    fn push_jmp(&mut self, i: usize, offset: i32, cond: Expr) {
        if offset > 0 {
            // Jump target is i + offset + 1 (offset is relative to next instruction)
            let target_idx = i + offset as usize + 1;

            // Check for loop exit condition FIRST:
            // If we're in a loop and this forward jump skips over the loop's back-edge
            // (a JAlways that returns to our loop start), then it's a loop exit.
            // This takes priority over guard clause detection.
            let is_loop_exit = self.scopes.last_loop_start().map(|loop_start| {
                // Scan from current position to end of function for a JAlways back to loop_start
                // that we would skip over with this jump
                (i + 1..self.f.ops.len()).any(|j| {
                    // Check if j is before or at target, and j has a JAlways back to loop_start
                    j < target_idx && matches!(
                        self.f.ops.get(j),
                        Some(Opcode::JAlways { offset }) if (j as i32 + *offset + 1) as usize == loop_start
                    )
                })
            }).unwrap_or(false);

            if is_loop_exit {
                if let Some(loop_cond) = self.scopes.last_loop_cond_mut() {
                    // If the loop condition is still the default `true`, this exit condition
                    // should become the actual loop condition
                    if matches!(loop_cond, Expr::Constant(Constant::Bool(true))) {
                        *loop_cond = cond;
                        return; // Don't create an if scope - this IS the loop condition
                    }
                }
            }

            // Check for guard clause pattern: jump to a return statement
            // (only if NOT a loop exit condition)
            if let Some(&Opcode::Ret { ret }) = self.f.ops.get(target_idx) {
                // This is a guard clause - emit "if (inverted_cond) return;"
                // The cond is the "stay" condition, so we need to invert it for the "jump" condition
                let guard_cond = not(cond.clone());
                let ret_value = if self.f.regtype(ret).is_void() {
                    None
                } else {
                    // Try to get the return value expression if available
                    Some(self.expr(ret))
                };
                self.push_stmt(Statement::IfElse {
                    cond: guard_cond,
                    if_: vec![Statement::Return(ret_value)],
                    else_: vec![],
                });
                return;
            }

            // It's an if (or nested condition in loop)
            // Save register state before entering if scope so null assignments inside
            // the if can be restored after it closes (to prevent null.array patterns)
            self.saved_reg_states.push(self.reg_state.clone());
            // Track which registers are set to null inside this if
            self.set_to_null_in_scope.push(HashSet::new());
            self.scopes.push_if(offset + 1, cond);
        }
    }
}

/// Decompile a function code to a list of [Statement]s.
/// This works by analyzing each opcodes in order while trying to reconstruct scopes, contexts and intents.
pub fn decompile_code(code: &Bytecode, f: &Function) -> Vec<Statement> {
    let mut state = DecompilerState::new(code, f);

    let iter = f.ops.iter().enumerate();
    for (i, o) in iter {
        // Check if we're at a catch block start
        state.check_catch_start(i);

        // Check if we've reached a switch case offset position
        // This needs to happen BEFORE processing the opcode
        // For combined cases like `case 0, 1, 2:`, multiple indices share the same offset
        if let Some(offsets) = state.scopes.last_is_switch_ctx() {
            // Find ALL case indices that point to this offset (for combined cases)
            let matching_patterns: Vec<usize> = offsets.iter()
                .enumerate()
                .filter(|(_, &offset)| offset == i)
                .map(|(idx, _)| idx)
                .collect();

            if !matching_patterns.is_empty() {
                // Note: We intentionally do NOT restore register state here.
                // The JIT discards register bindings at jump targets, but for decompilation
                // we want values to flow through. The if/else scope handling will restore
                // registers that were set to null, which handles the ternary pattern.
                state.scopes.push_switch_case(matching_patterns);
            }
        }

        // Opcodes are grouped by semantic
        // Control flow first because they are the most important
        match o {
            //region CONTROL FLOW
            &Opcode::JTrue { cond, offset } => state.push_jmp(i, offset, not(state.expr_at(cond, i))),
            &Opcode::JFalse { cond, offset } => state.push_jmp(i, offset, state.expr_at(cond, i)),
            &Opcode::JNull { reg, offset } => {
                // If the register currently holds null, force it into a variable.
                // This prevents "null.field" in the else-branch where we know it's not null.
                if matches!(state.reg_state.get(&reg), Some(Expr::Constant(Constant::Null))) {
                    state.ensure_variable(reg);
                }
                state.push_jmp(i, offset, noteq(state.expr_at(reg, i), cst_null()))
            }
            &Opcode::JNotNull { reg, offset } => {
                // If the register currently holds null, force it into a variable.
                // This prevents "null.field" in the then-branch where we know it's not null.
                if matches!(state.reg_state.get(&reg), Some(Expr::Constant(Constant::Null))) {
                    state.ensure_variable(reg);
                }
                state.push_jmp(i, offset, eq(state.expr_at(reg, i), cst_null()))
            }
            &Opcode::JSGte { a, b, offset } | &Opcode::JUGte { a, b, offset } => {
                state.push_jmp(i, offset, gt(state.expr_at(b, i), state.expr_at(a, i)))
            }
            &Opcode::JSGt { a, b, offset } => {
                state.push_jmp(i, offset, gte(state.expr_at(b, i), state.expr_at(a, i)))
            }
            &Opcode::JSLte { a, b, offset } => {
                state.push_jmp(i, offset, lt(state.expr_at(b, i), state.expr_at(a, i)))
            }
            &Opcode::JSLt { a, b, offset } | &Opcode::JULt { a, b, offset } => {
                state.push_jmp(i, offset, lte(state.expr_at(b, i), state.expr_at(a, i)))
            }
            &Opcode::JNotLt { a, b, offset } => {
                // JNotLt: jump if a >= b (not a < b)
                state.push_jmp(i, offset, lt(state.expr_at(a, i), state.expr_at(b, i)))
            }
            &Opcode::JNotGte { a, b, offset } => {
                // JNotGte: jump if a < b (not a >= b)
                state.push_jmp(i, offset, gte(state.expr_at(a, i), state.expr_at(b, i)))
            }
            &Opcode::JEq { a, b, offset } => {
                state.push_jmp(i, offset, noteq(state.expr_at(a, i), state.expr_at(b, i)))
            }
            &Opcode::JNotEq { a, b, offset } => {
                state.push_jmp(i, offset, eq(state.expr_at(a, i), state.expr_at(b, i)))
            }
            // Unconditional jumps can actually mean a lot of things
            &Opcode::JAlways { offset } => {
                if offset < 0 {
                    // It's either the jump backward of a loop or a continue statement
                    if let Some(loop_start) = state.scopes.last_loop_start() {
                        // Scan the next instructions in order to find another jump to the same place
                        if f.ops.iter().enumerate().skip(i + 1).find_map(|(j, o)| {
                            // We found another jump to the same place !
                            if matches!(o, Opcode::JAlways {offset} if (j as i32 + offset + 1) as usize == loop_start) {
                                Some(true)
                            } else {
                                None
                            }
                        }).unwrap_or(false) {
                            // If this jump is not the last jump backward for the current loop, so it's definitely a continue; statement
                            state.push_stmt(Statement::Continue);
                        } else {
                            // It's the last jump backward of the loop, which means the end of the loop
                            // we generate the loop statement
                            if let Some(stmt) = state.scopes.end_last_loop() {
                                state.push_stmt(stmt);
                                // Pop the loop counter set for this loop
                                state.loop_counters.pop();
                            } else {
                                // Fallback: emit comment instead of panicking
                                state.push_stmt(Statement::Comment(format!(
                                    "JAlways {} (backward jump but no loop scope)",
                                    offset
                                )));
                            }
                        }
                    } else {
                        // Fallback: backward jump but no loop context
                        state.push_stmt(Statement::Comment(format!(
                            "JAlways {} (backward jump, no loop context)",
                            offset
                        )));
                    }
                } else {
                    // Check if this JAlways is skipping a catch block (handled by EndTrap)
                    if state.pending_try_info.take().is_some() {
                        // This JAlways was already handled by EndTrap - skip it
                        // The pending catch is already set up
                    } else if state.scopes.last_is_if() {
                        // It's the jump over of an else clause
                        // Pop the if's null-tracking and saved state
                        state.set_to_null_in_scope.pop();
                        state.saved_reg_states.pop();
                        // Save current state (includes values set in if-branch) for else.
                        // This allows restoration to work for ternary-style patterns like:
                        //   r12 = if (cond) cast(x) else null
                        // When else sets r12 to null, we can restore to the cast from if.
                        state.saved_reg_states.push(state.reg_state.clone());
                        state.set_to_null_in_scope.push(HashSet::new());
                        state.scopes.push_else(offset + 1);
                    } else if state.scopes.last_is_switch_ctx().is_some() {
                        // Switch case transitions are handled by the pre-opcode check
                        // at the start of the loop - no action needed here
                    } else if state.scopes.last_loop_start().is_some() {
                        // Check the instruction just before the jump target
                        // If it's a jump backward of a loop
                        if matches!(f.ops[(i as i32 + offset) as usize], Opcode::JAlways {offset} if offset < 0)
                        {
                            // It's a break condition
                            state.push_stmt(Statement::Break);
                        }
                        // TODO else
                    } else {
                        // FALLBACK: Emit a comment instead of failing
                        // This allows decompilation to continue with readable output
                        state.push_stmt(Statement::Comment(format!(
                            "JAlways +{} (forward jump to op {})",
                            offset,
                            i as i32 + offset
                        )));
                    }
                }
            }
            Opcode::Switch { reg, offsets, end } => {
                // Save register state before entering switch.
                // Each case will restore this state to prevent register bleeding between cases.
                state.switch_saved_states.push(state.reg_state.clone());

                // Check if this switch is on an EnumIndex result (for enum pattern matching)
                // If so, look up the enum type for constructor name lookup during formatting
                let enum_type = state.enum_index_sources.get(reg).map(|&src_reg| f.regtype(src_reg));

                // Convert to absolute positions (offsets are relative to instruction AFTER switch)
                state.scopes.push_switch(
                    *end + 1,
                    state.expr(*reg),
                    offsets.iter().map(|o| i + 1 + *o as usize).collect(),
                    enum_type,
                );
                // The default switch case is implicit
            }
            &Opcode::Label => {
                // Only create a loop scope if there's a backward JAlways that jumps to this Label
                // Labels can also be targets for forward jumps (switch fall-through, etc.)
                let loop_end = f.ops.iter().enumerate().skip(i + 1).find_map(|(j, op)| {
                    if matches!(op, Opcode::JAlways { offset } if (j as i32 + *offset + 1) as usize == i) {
                        Some(j)
                    } else {
                        None
                    }
                });
                if let Some(loop_end_pos) = loop_end {
                    // Detect variables that need hoisting - assigned in loop but used after
                    let to_hoist = detect_hoisting_needed(&f.ops, i, loop_end_pos, f, code);
                    for (reg, debug_name) in to_hoist {
                        // Create variable name and emit uninitialized declaration
                        let var_name = debug_name.unwrap_or_else(|| {
                            let n: Str = format!("v{}", state.synthetic_var_counter).into();
                            state.synthetic_var_counter += 1;
                            n
                        });
                        // Only emit if not already declared
                        if !state.name_to_reg.contains_key(&var_name) {
                            state.name_to_reg.insert(var_name.clone(), reg);
                            state.reg_state.insert(reg, Expr::Variable(reg, Some(var_name.clone())));
                            state.push_stmt(Statement::VarDecl {
                                name: var_name,
                            });
                        }
                    }

                    // Detect loop counters (registers with Incr ops) and track them
                    // This ensures loop counters are treated as variables from the start,
                    // so loop conditions like `while (index < arr.length)` work correctly
                    let counters = detect_loop_counters(&f.ops, i);

                    // For each counter, ensure it has a variable expression in reg_state
                    // This is needed so that when we process the loop exit condition,
                    // the counter register shows as a variable, not a constant
                    for &counter_reg in &counters {
                        if !matches!(state.reg_state.get(&counter_reg), Some(Expr::Variable(_, _))) {
                            let name = state.var_name(counter_reg);
                            state.reg_state.insert(counter_reg, Expr::Variable(counter_reg, Some(name)));
                        }
                    }

                    state.loop_counters.push(counters);
                    state.scopes.push_loop(i);
                }
                // If not a loop target, the Label is just a forward jump target - no scope needed
            }
            &Opcode::Ret { ret } => {
                // Do not display return void; only in case of an early return
                if state.scopes.has_scopes() {
                    state.push_stmt(Statement::Return(if f.regtype(ret).is_void() {
                        None
                    } else {
                        Some(state.expr_at(ret, i))
                    }));
                } else if !f.regtype(ret).is_void() {
                    state.push_stmt(Statement::Return(Some(state.expr_at(ret, i))));
                }
            }
            //endregion

            //region EXCEPTIONS
            &Opcode::Throw { exc } | &Opcode::Rethrow { exc } => {
                state.push_stmt(Statement::Throw(state.expr(exc)));
            }
            &Opcode::Trap { exc, offset } => {
                // Calculate catch block start address: current op + offset + 1
                let catch_start = i + offset as usize + 1;
                state.scopes.push_try(exc, catch_start);
            }
            &Opcode::EndTrap { exc: triggered } => {
                // exc field is actually a "triggered" flag:
                // 0 = early exit from try (return inside try block) - don't close
                // 1 = normal end of try block, catch follows - close the scope
                if triggered.0 == 0 {
                    // Early exit from try - just emit cleanup, don't close scope
                    continue;
                }
                // Close the Try scope and prepare for the catch block
                if let Some((exc, catch_start, try_stmts)) = state.scopes.close_try() {
                    // Look ahead to see if the next instruction is a forward JAlways (catch skip)
                    // If so, we can calculate the catch length and queue the catch block.
                    if let Some(Opcode::JAlways { offset }) = f.ops.get(i + 1) {
                        if *offset > 0 {
                            // Next instruction is a forward JAlways that skips the catch
                            // catch_end = (i+1) + offset + 1
                            let catch_end = i + 2 + *offset as usize;
                            let catch_len = (catch_end - catch_start) as i32;
                            // Queue the catch with try_stmts - TryCatch will be emitted when catch scope closes
                            state.pending_catches.push((catch_start, exc, catch_len, try_stmts));
                            // Mark that we've handled this JAlways
                            state.pending_try_info = Some((catch_start, exc));
                        } else {
                            // Backward jump - catch is empty, emit TryCatch with empty catch
                            state.push_stmt(Statement::TryCatch {
                                try_stmts,
                                catch_var: "e".to_string(),
                                catch_stmts: Vec::new(),
                            });
                        }
                    } else {
                        // No JAlways follows - catch block starts immediately
                        // Scan forward to find catch block end (ORethrow, or end of function)
                        let mut catch_end = f.ops.len();
                        for j in catch_start..f.ops.len() {
                            match &f.ops[j] {
                                Opcode::Rethrow { .. } => {
                                    catch_end = j + 1; // Include the rethrow
                                    break;
                                }
                                Opcode::Ret { .. } => {
                                    // Check if next op is Rethrow (pattern: conditional return then rethrow)
                                    if j + 1 < f.ops.len() {
                                        if matches!(f.ops[j + 1], Opcode::Rethrow { .. }) {
                                            catch_end = j + 2; // Include both
                                            break;
                                        }
                                    }
                                }
                                _ => {}
                            }
                        }
                        let catch_len = (catch_end - catch_start) as i32;
                        // Register the exception variable for the catch scope
                        state.reg_state.insert(exc, Expr::Variable(exc, Some("e".into())));
                        state.scopes.push_catch(exc, catch_len, try_stmts);
                    }
                } else {
                    // No Try scope found - emit comment
                    state.push_stmt(Statement::Comment(format!(
                        "EndTrap at op {} but no Try scope found",
                        i
                    )));
                }
            }
            //endregion

            //region CONSTANTS
            &Opcode::Int { dst, ptr } => {
                // Check if this register is a loop counter - if so, emit as variable declaration
                // This handles the case where `Int reg = 0` (loop init) happens BEFORE the Label
                if state.all_loop_counters.contains(&dst) {
                    let var_name: Str = format!("v{}", state.synthetic_var_counter).into();
                    state.synthetic_var_counter += 1;
                    let var_expr = Expr::Variable(dst, Some(var_name.clone()));
                    let declaration = !state.name_to_reg.contains_key(&var_name);
                    state.name_to_reg.insert(var_name.clone(), dst);
                    state.push_stmt(Statement::Assign {
                        declaration,
                        variable: var_expr.clone(),
                        assign: cst_int(ptr),
                    });
                    state.reg_state.insert(dst, var_expr);
                } else {
                    state.push_expr(i, dst, cst_int(ptr));
                }
            }
            &Opcode::Float { dst, ptr } => {
                state.push_expr(i, dst, cst_float(ptr));
            }
            &Opcode::Bool { dst, value } => {
                state.push_expr(i, dst, cst_bool(value));
            }
            &Opcode::String { dst, ptr } => {
                state.push_expr(i, dst, cst_string(ptr));
            }
            &Opcode::Null { dst } => {
                state.push_expr(i, dst, cst_null());
            }
            &Opcode::Type { dst, ty } => {
                state.push_expr(i, dst, cst_type(ty));
            }
            //endregion

            //region OPERATORS
            &Opcode::Mov { dst, src } => {
                let src_expr = state.expr(src);
                state.push_expr(i, dst, src_expr.clone());
                // Break expression chains to prevent stack overflow on drop.
                // If src already has a Variable (like a named loop counter), don't overwrite it.
                // Only create a synthetic variable for complex expressions.
                if !matches!(&src_expr, Expr::Variable(_, _)) {
                    let name = f.var_name(code, i).or_else(|| {
                        state.synthetic_var_counter += 1;
                        Some(format!("v{}", state.synthetic_var_counter - 1).into())
                    });
                    // Use src register index (not dst!) so the variable refers to the correct register
                    state.reg_state.insert(src, Expr::Variable(src, name));
                }
            }
            &Opcode::Add { dst, a, b } => {
                state.push_expr(i, dst, add(state.expr_at(a, i), state.expr_at(b, i)));
            }
            &Opcode::Sub { dst, a, b } => {
                state.push_expr(i, dst, sub(state.expr_at(a, i), state.expr_at(b, i)));
            }
            &Opcode::Mul { dst, a, b } => {
                state.push_expr(i, dst, mul(state.expr_at(a, i), state.expr_at(b, i)));
            }
            &Opcode::SDiv { dst, a, b } | &Opcode::UDiv { dst, a, b } => {
                state.push_expr(i, dst, div(state.expr_at(a, i), state.expr_at(b, i)));
            }
            &Opcode::SMod { dst, a, b } | &Opcode::UMod { dst, a, b } => {
                state.push_expr(i, dst, modulo(state.expr_at(a, i), state.expr_at(b, i)));
            }
            &Opcode::Shl { dst, a, b } => {
                state.push_expr(i, dst, shl(state.expr_at(a, i), state.expr_at(b, i)));
            }
            &Opcode::SShr { dst, a, b } | &Opcode::UShr { dst, a, b } => {
                state.push_expr(i, dst, shr(state.expr_at(a, i), state.expr_at(b, i)));
            }
            &Opcode::And { dst, a, b } => {
                state.push_expr(i, dst, and(state.expr_at(a, i), state.expr_at(b, i)));
            }
            &Opcode::Or { dst, a, b } => {
                state.push_expr(i, dst, or(state.expr_at(a, i), state.expr_at(b, i)));
            }
            &Opcode::Xor { dst, a, b } => {
                state.push_expr(i, dst, xor(state.expr_at(a, i), state.expr_at(b, i)));
            }
            &Opcode::Neg { dst, src } => {
                state.push_expr(i, dst, neg(state.expr_at(src, i)));
            }
            &Opcode::Not { dst, src } => {
                state.push_expr(i, dst, not(state.expr_at(src, i)));
            }
            &Opcode::Incr { dst } => {
                // Ensure we have a variable to increment (not a constant like "0")
                let var_expr = state.ensure_variable(dst);
                state.push_stmt(stmt(incr(var_expr)));
            }
            &Opcode::Decr { dst } => {
                // Ensure we have a variable to decrement (not a constant)
                let var_expr = state.ensure_variable(dst);
                state.push_stmt(stmt(decr(var_expr)));
            }
            //endregion

            //region CALLS
            &Opcode::Call0 { dst, fun } => {
                if fun.ty(code).ret.is_void() {
                    state.push_stmt(stmt(call_fun(fun, Vec::new())));
                } else {
                    state.push_expr(i, dst, call_fun(fun, Vec::new()));
                }
            }
            &Opcode::Call1 { dst, fun, arg0 } => {
                state.push_call(i, dst, fun, &[arg0]);
            }
            &Opcode::Call2 {
                dst,
                fun,
                arg0,
                arg1,
            } => {
                state.push_call(i, dst, fun, &[arg0, arg1]);
            }
            &Opcode::Call3 {
                dst,
                fun,
                arg0,
                arg1,
                arg2,
            } => {
                state.push_call(i, dst, fun, &[arg0, arg1, arg2]);
            }
            &Opcode::Call4 {
                dst,
                fun,
                arg0,
                arg1,
                arg2,
                arg3,
            } => {
                state.push_call(i, dst, fun, &[arg0, arg1, arg2, arg3]);
            }
            Opcode::CallN { dst, fun, args } => {
                // Check if this is a constructor call
                if let Some(&ExprCtx::Constructor { reg, pos }) = state.expr_ctx.last() {
                    if reg == args[0] {
                        state.push_expr(
                            pos,
                            reg,
                            Expr::Constructor(ConstructorCall::new(
                                f.regtype(reg),
                                state.args_expr(&args[1..]),
                            )),
                        );
                        state.expr_ctx.pop();
                        continue;
                    }
                    // Not a constructor call - fall through to normal handling
                }

                // Normal function call
                state.push_stmt(comment(fun.display::<EnhancedFmt>(code).to_string()));
                let call = call_fun(*fun, state.args_expr(args));
                if fun.ty(code).ret.is_void() {
                    state.push_stmt(stmt(call));
                } else {
                    // For function calls, create synthetic variable for readability
                    let name = f.var_name(code, i);
                    if name.is_some() {
                        state.push_expr(i, *dst, call);
                    } else {
                        let var_name: Str = format!("v{}", state.synthetic_var_counter).into();
                        state.synthetic_var_counter += 1;
                        let var_expr = Expr::Variable(*dst, Some(var_name.clone()));

                        let declaration = !state.name_to_reg.contains_key(&var_name);
                        state.name_to_reg.insert(var_name.clone(), *dst);
                        state.push_stmt(Statement::Assign {
                            declaration,
                            variable: var_expr.clone(),
                            assign: call,
                        });
                        state.reg_state.insert(*dst, var_expr);
                    }
                }
            }
            Opcode::CallMethod { dst, field, args } => {
                let call = call(
                    ast::field(state.expr(args[0]), f.regtype(args[0]), *field, code),
                    state.args_expr(&args[1..]),
                );
                if f.regtype(args[0])
                    .method(field.0, code)
                    .and_then(|p| p.findex.as_fn(code))
                    .map(|fun| fun.ty(code).ret.is_void())
                    .unwrap_or(false)
                {
                    state.push_stmt(stmt(call));
                } else {
                    state.push_expr(i, *dst, call);
                }
            }
            Opcode::CallThis { dst, field, args } => {
                // Method lookup may fail if pindex not found in inheritance chain
                let method = f.regs[0].method(field.0, code);
                let method_name = method
                    .map(|m| m.name(code))
                    .unwrap_or_else(|| format!("method_{}", field.0).into());
                let call = call(
                    Expr::Field(Box::new(cst_this()), method_name),
                    state.args_expr(args),
                );
                let is_void = method
                    .and_then(|m| m.findex.as_fn(code))
                    .map(|fun| fun.ty(code).ret.is_void())
                    .unwrap_or(false);
                if is_void {
                    state.push_stmt(stmt(call));
                } else {
                    state.push_expr(i, *dst, call);
                }
            }
            Opcode::CallClosure { dst, fun, args } => {
                let call = call(state.expr(*fun), state.args_expr(args));
                if f.regtype(*fun)
                    .as_fun(code)
                    .map(|ty| ty.ret.is_void())
                    .unwrap_or(false)
                {
                    state.push_stmt(stmt(call));
                } else {
                    state.push_expr(i, *dst, call);
                }
            }
            //endregion

            //region CLOSURES
            &Opcode::StaticClosure { dst, fun } => {
                state.push_stmt(comment(format!(
                    "closure : {}",
                    fun.display::<EnhancedFmt>(code)
                )));
                // Handle native functions gracefully - can't decompile them
                if let Some(func) = fun.as_fn(code) {
                    state.push_expr(
                        i,
                        dst,
                        Expr::Closure(fun, decompile_code(code, func)),
                    );
                } else {
                    // Native closure - just reference by name
                    state.push_expr(i, dst, Expr::FunRef(fun));
                }
            }
            &Opcode::InstanceClosure { dst, obj, fun } => {
                state.push_stmt(comment(format!(
                    "closure : {}",
                    fun.display::<EnhancedFmt>(code)
                )));
                match &code[f[obj]] {
                    // This is an anonymous enum holding the capture for the closure
                    Type::Enum { .. } => {
                        // Handle native functions gracefully
                        if let Some(func) = fun.as_fn(code) {
                            state.push_expr(
                                i,
                                dst,
                                Expr::Closure(fun, decompile_code(code, func)),
                            );
                        } else {
                            // Native closure - just reference by name
                            state.push_expr(i, dst, Expr::FunRef(fun));
                        }
                    }
                    _ => {
                        state.push_expr(
                            i,
                            dst,
                            Expr::Field(Box::new(state.expr(obj)), fun.name(code)),
                        );
                    }
                }
            }
            //endregion

            //region ACCESSES
            &Opcode::NullCheck { reg } => {
                // Emit comment to help track down null pointer issues
                // Try to show variable name instead of register number
                let expr = state.expr(reg);
                let expr_str = match &expr {
                    Expr::Variable(_, Some(name)) => name.to_string(),
                    Expr::Ident(name) => name.to_string(),
                    Expr::Field(base, field) => {
                        // Try to get a simple representation like "obj.field"
                        match base.as_ref() {
                            Expr::Ident(name) => format!("{}.{}", name, field),
                            Expr::Variable(_, Some(name)) => format!("{}.{}", name, field),
                            Expr::Constant(Constant::This) => format!("this.{}", field),
                            _ => format!("_.{}", field),
                        }
                    }
                    Expr::Constant(Constant::This) => "this".to_string(),
                    _ => format!("r{}", reg.0),
                };
                state.push_stmt(comment(format!("nullcheck {}", expr_str)));
            }
            &Opcode::GetGlobal { dst, global } => {
                // Is a string
                if f[dst].0 == 13 {
                    state.push_expr(
                        i,
                        dst,
                        cst_string(RefString(
                            code.globals_initializers
                                .get(&global)
                                .and_then(|&x| {
                                    code.constants
                                        .as_ref()
                                        .map(|constants| constants[x].fields[0])
                                })
                                .unwrap_or(0),
                        )),
                    );
                } else {
                    match &code[f[dst]] {
                        Type::Obj(obj) | Type::Struct(obj) => {
                            state.push_expr(
                                i,
                                dst,
                                Expr::Variable(dst, Some(code[obj.name].to_owned())),
                            );
                        }
                        Type::Enum { name, constructs, .. } => {
                            let dst_type = f[dst];
                            // Look up the enum construct from the constant initializer
                            let construct_idx = code.globals_initializers
                                .get(&global)
                                .and_then(|&const_idx| {
                                    code.constants.as_ref().and_then(|constants| {
                                        constants.get(const_idx).and_then(|constant_def| {
                                            constant_def.fields.first().copied()
                                        })
                                    })
                                })
                                .or_else(|| {
                                    // Fallback: determine position among all globals of this enum type
                                    // This assumes globals are created in construct order
                                    let mut enum_globals: Vec<usize> = code
                                        .globals
                                        .iter()
                                        .enumerate()
                                        .filter(|(_, &t)| t == dst_type)
                                        .map(|(i, _)| i)
                                        .collect();
                                    enum_globals.sort();
                                    enum_globals.iter().position(|&g| g == global.0)
                                });

                            let enum_name = &code[*name];
                            if let Some(idx) = construct_idx {
                                if let Some(construct) = constructs.get(idx) {
                                    // Format as EnumType.Variant
                                    state.push_expr(
                                        i,
                                        dst,
                                        Expr::Variable(dst, Some(format!("{}.{}", enum_name, &code[construct.name]).into())),
                                    );
                                } else {
                                    state.push_expr(
                                        i,
                                        dst,
                                        Expr::Unknown(format!("{}.[idx {}]", enum_name, idx)),
                                    );
                                }
                            } else {
                                state.push_expr(
                                    i,
                                    dst,
                                    Expr::Unknown(format!("{}.[?]", enum_name)),
                                );
                            }
                        }
                        _ => {
                            // For abstract types, references, etc., emit as global identifier
                            state.push_expr(
                                i,
                                dst,
                                Expr::Ident(format!("@G{}", global.0).into()),
                            );
                        }
                    }
                }
            }
            &Opcode::SetGlobal { global, src } => {
                // @global = src
                state.push_stmt(Statement::Assign {
                    declaration: false,
                    variable: Expr::Ident(format!("@G{}", global.0).into()),
                    assign: state.expr(src),
                });
            }
            &Opcode::Bytes { dst, ptr: _ } => {
                // Load bytes constant
                state.push_expr(i, dst, Expr::Ident("bytes".into()));
            }
            &Opcode::Field { dst, obj, field } => {
                state.push_expr(
                    i,
                    dst,
                    ast::field(state.expr(obj), f.regtype(obj), field, code),
                );
            }
            &Opcode::SetField { obj, field, src } => {
                let ctx = state.expr_ctx.pop();
                // Might be a SetField for an anonymous structure - check register matches
                if let Some(ExprCtx::Anonymous {
                    reg,
                    pos,
                    mut fields,
                    mut remaining,
                }) = ctx
                {
                    if reg == obj {
                        // This SetField is for the anonymous object we're tracking
                        fields.insert(field, state.expr(src));
                        remaining -= 1;
                        // If we filled all the structure fields, we emit an expr
                        if remaining == 0 {
                            state.push_expr(pos, obj, Expr::Anonymous(f.regtype(obj), fields));
                        } else {
                            state.expr_ctx.push(ExprCtx::Anonymous {
                                reg,
                                pos,
                                fields,
                                remaining,
                            });
                        }
                    } else {
                        // This SetField is for a different object, push context back
                        state.expr_ctx.push(ExprCtx::Anonymous {
                            reg,
                            pos,
                            fields,
                            remaining,
                        });
                        // Fall through to normal field set
                        state.push_stmt(Statement::Assign {
                            declaration: false,
                            variable: ast::field(state.expr(obj), f.regtype(obj), field, code),
                            assign: state.expr(src),
                        });
                    }
                } else if let Some(ctx) = ctx {
                    state.expr_ctx.push(ctx);
                } else {
                    // Otherwise this is just a normal field set
                    state.push_stmt(Statement::Assign {
                        declaration: false,
                        variable: ast::field(state.expr(obj), f.regtype(obj), field, code),
                        assign: state.expr(src),
                    });
                }
            }
            &Opcode::GetThis { dst, field } => {
                state.push_expr(i, dst, ast::field(cst_this(), f.regs[0], field, code));
            }
            &Opcode::SetThis { field, src } => {
                state.push_stmt(Statement::Assign {
                    declaration: false,
                    variable: ast::field(cst_this(), f.regs[0], field, code),
                    assign: state.expr(src),
                });
            }
            &Opcode::DynGet { dst, obj, field } => {
                state.push_expr(i, dst, array(state.expr(obj), cst_string(field)));
            }
            &Opcode::DynSet { obj, field, src } => {
                state.push_stmt(Statement::Assign {
                    declaration: false,
                    variable: array(state.expr(obj), cst_string(field)),
                    assign: state.expr(src),
                });
            }
            //endregion

            //region VALUES
            &Opcode::ToDyn { dst, src }
            | &Opcode::ToSFloat { dst, src }
            | &Opcode::ToUFloat { dst, src }
            | &Opcode::ToInt { dst, src }
            | &Opcode::SafeCast { dst, src }
            | &Opcode::UnsafeCast { dst, src }
            | &Opcode::ToVirtual { dst, src } => {
                state.push_expr(i, dst, state.expr(src));
            }
            &Opcode::Ref { dst, src } => {
                // ORef creates a reference. If source has no expression (used as output
                // parameter storage), create a synthetic variable name.
                let src_expr = if state.reg_state.contains_key(&src) {
                    state.expr(src)
                } else {
                    // Create synthetic variable for uninitialized ref storage
                    state.synthetic_var_counter += 1;
                    let var_name = format!("_ref{}", state.synthetic_var_counter);
                    let expr = Expr::Variable(src, Some(var_name.into()));
                    state.reg_state.insert(src, expr.clone());
                    expr
                };
                state.push_expr(i, dst, src_expr);
            }
            &Opcode::Unref { dst, src } => {
                state.push_expr(i, dst, state.expr(src));
            }
            &Opcode::Setref { dst, value } => {
                state.push_stmt(Statement::Assign {
                    declaration: false,
                    variable: state.expr(dst),
                    assign: state.expr(value),
                });
            }
            &Opcode::RefData { dst, src } => {
                state.push_expr(i, dst, state.expr(src));
            }
            &Opcode::GetTID { dst, src } => {
                // typeid(src) - returns integer type kind for switch statements
                let src_expr = state.expr(src);
                state.push_expr(
                    i,
                    dst,
                    Expr::Call(Box::new(Call::new(Expr::Ident("typeid".into()), vec![src_expr]))),
                );
            }
            &Opcode::GetType { dst, src } => {
                // typeof(src) - returns the runtime type object
                let src_expr = state.expr(src);
                state.push_expr(
                    i,
                    dst,
                    Expr::Call(Box::new(Call::new(Expr::Ident("typeof".into()), vec![src_expr]))),
                );
            }
            &Opcode::VirtualClosure { dst, obj, field } => {
                // Virtual method closure: field is a proto index (NOT a register)
                // Despite field being typed as Reg, it's actually a constant proto index
                let obj_expr = state.expr(obj);
                // field.0 gives us the raw index value
                let proto_idx = field.0;
                state.push_expr(
                    i,
                    dst,
                    Expr::Call(Box::new(Call::new(
                        Expr::Ident("vclosure".into()),
                        vec![obj_expr, Expr::Ident(format!("proto[{}]", proto_idx).into())],
                    ))),
                );
            }
            &Opcode::GetI8 { dst, bytes, index } => {
                // bytes[index] for 8-bit access
                let bytes_expr = state.expr(bytes);
                let index_expr = state.expr(index);
                state.push_expr(i, dst, Expr::Array(Box::new(bytes_expr), Box::new(index_expr)));
            }
            &Opcode::GetI16 { dst, bytes, index } => {
                // bytes[index] for 16-bit access
                let bytes_expr = state.expr(bytes);
                let index_expr = state.expr(index);
                state.push_expr(i, dst, Expr::Array(Box::new(bytes_expr), Box::new(index_expr)));
            }
            &Opcode::SetI8 { bytes, index, src } | &Opcode::SetI16 { bytes, index, src } => {
                // bytes[index] = src
                let bytes_expr = state.expr(bytes);
                let index_expr = state.expr(index);
                let src_expr = state.expr(src);
                state.push_stmt(Statement::Assign {
                    declaration: false,
                    variable: Expr::Array(Box::new(bytes_expr), Box::new(index_expr)),
                    assign: src_expr,
                });
            }
            &Opcode::New { dst } => {
                // Constructor analysis
                match &code[f[dst]] {
                    Type::Obj(_) | Type::Struct(_) => {
                        // Store constructor expression in reg_state only (no statement yet).
                        // If a constructor call follows, it will create the final statement with args.
                        // Otherwise field assignments will use this object directly.
                        state.reg_state.insert(
                            dst,
                            Expr::Constructor(ConstructorCall::new(f.regtype(dst), Vec::new())),
                        );
                        state
                            .expr_ctx
                            .push(ExprCtx::Constructor { reg: dst, pos: i });
                    }
                    Type::Virtual { fields } => {
                        // Store immediate expression so register is always tracked
                        // even if context is consumed or fields set after
                        state.push_expr(
                            i,
                            dst,
                            Expr::Anonymous(f.regtype(dst), HashMap::new()),
                        );
                        state.expr_ctx.push(ExprCtx::Anonymous {
                            reg: dst,
                            pos: i,
                            fields: HashMap::with_capacity(fields.len()),
                            remaining: fields.len(),
                        });
                    }
                    _ => {
                        state.push_expr(
                            i,
                            dst,
                            Expr::Constructor(ConstructorCall::new(f.regtype(dst), Vec::new())),
                        );
                    }
                }
            }
            //endregion

            //region ENUMS
            &Opcode::EnumAlloc { dst, construct } => {
                state.push_expr(
                    i,
                    dst,
                    Expr::EnumConstr(f.regtype(dst), construct, Vec::new()),
                );
            }
            Opcode::MakeEnum {
                dst,
                construct,
                args,
            } => {
                state.push_expr(
                    i,
                    *dst,
                    Expr::EnumConstr(f.regtype(*dst), *construct, state.args_expr(args)),
                );
            }
            &Opcode::EnumIndex { dst, value } => {
                // Track that dst holds an enum index extracted from `value`
                // This is used later to reconstruct enum pattern matching
                state.enum_index_sources.insert(dst, value);

                // Use Type.enumIndex(value) which is valid Haxe
                state.push_expr(
                    i,
                    dst,
                    Expr::Call(Box::new(Call::new(
                        Expr::Field(Box::new(Expr::Ident("Type".into())), Str::from("enumIndex")),
                        vec![state.expr(value)],
                    ))),
                );
            }
            &Opcode::EnumField {
                dst,
                value,
                construct: _,
                field,
            } => {
                // Check if this is a closure capture access:
                // - value is Reg(0) (first parameter)
                // - first param is an enum type
                // - function has captured variables (assigns with position == usize::MAX)
                let has_captured_vars = f.assigns.as_ref()
                    .map(|a| a.iter().any(|(_, pos)| *pos == usize::MAX))
                    .unwrap_or(false);
                let is_closure_capture = value == Reg(0)
                    && has_captured_vars
                    && f.regs.first().map(|r| matches!(&code[*r], Type::Enum { .. })).unwrap_or(false);

                if is_closure_capture {
                    // Look up captured variable name from assigns metadata
                    // Captured variables have position usize::MAX in assigns
                    let captured_name = f.assigns.as_ref().and_then(|assigns| {
                        // Filter to only captured variables (position == usize::MAX)
                        let captured: Vec<_> = assigns.iter()
                            .filter(|(_, pos)| *pos == usize::MAX)
                            .collect();
                        // The field index corresponds to the order of captured variables
                        captured.get(field.0 as usize).map(|(s, _)| code.get(*s).clone())
                    });

                    if let Some(name) = captured_name {
                        // Use the captured variable name directly
                        state.push_expr(i, dst, Expr::Ident(name));
                    } else {
                        // Fallback: use generic captured_N name
                        state.push_expr(i, dst, Expr::Ident(Str::from(format!("captured_{}", field.0))));
                    }
                } else {
                    // Regular enum field access - use Type.enumParameters(value)[field]
                    let enum_params = Expr::Call(Box::new(Call::new(
                        Expr::Field(Box::new(Expr::Ident("Type".into())), Str::from("enumParameters")),
                        vec![state.expr(value)],
                    )));
                    state.push_expr(
                        i,
                        dst,
                        Expr::Array(Box::new(enum_params), Box::new(Expr::Constant(Constant::InlineInt(field.0 as usize)))),
                    );
                }
            }
            &Opcode::SetEnumField { value, field, src } => match state.expr(value) {
                Expr::Variable(_r, _name) => {
                    state.push_stmt(Statement::Assign {
                        declaration: false,
                        variable: Expr::Field(
                            Box::new(state.expr(value)),
                            Str::from(field.0.to_string()),
                        ),
                        assign: state.expr(src),
                    });
                }
                _ => {
                    // Closure capture uses anonymous enum types that produce invalid syntax.
                    // Just emit a comment since the captured value is accessed via Type.enumParameters().
                    state.push_stmt(comment("closure capture (internal)"));
                }
            },
            //endregion

            //region ARRAYS
            &Opcode::ArraySize { dst, array } => {
                state.push_expr(
                    i,
                    dst,
                    Expr::Field(Box::new(state.expr(array)), Str::from("length")),
                );
            }
            &Opcode::GetArray { dst, array, index } => {
                state.push_expr(i, dst, ast::array(state.expr(array), state.expr(index)));
            }
            &Opcode::SetArray { array, index, src } => {
                state.push_stmt(Statement::Assign {
                    declaration: false,
                    variable: ast::array(state.expr(array), state.expr(index)),
                    assign: state.expr(src),
                });
            }
            //endregion

            //region MEM
            &Opcode::GetMem { dst, bytes, index } => {
                state.push_expr(i, dst, array(state.expr(bytes), state.expr(index)));
            }
            &Opcode::SetMem { bytes, index, src } => {
                state.push_stmt(Statement::Assign {
                    declaration: false,
                    variable: array(state.expr(bytes), state.expr(index)),
                    assign: state.expr(src),
                });
            }
            //endregion

            // No-op opcodes
            &Opcode::Nop => {}
            &Opcode::Assert => {
                state.push_stmt(comment("assert".to_string()));
            }

            // Unimplemented opcodes - emit loud warnings
            &Opcode::Asm { .. } => {
                state.push_stmt(comment("!!! UNHANDLED OPCODE: Asm - inline assembly !!!".to_string()));
                eprintln!("WARNING: Unhandled opcode Asm at op {} in function {:?}", i, f.name(code));
            }
            &Opcode::Prefetch { .. } => {
                state.push_stmt(comment("!!! UNHANDLED OPCODE: Prefetch - memory hint !!!".to_string()));
                eprintln!("WARNING: Unhandled opcode Prefetch at op {} in function {:?}", i, f.name(code));
            }
            &Opcode::RefOffset { .. } => {
                state.push_stmt(comment("!!! UNHANDLED OPCODE: RefOffset - reference with offset !!!".to_string()));
                eprintln!("WARNING: Unhandled opcode RefOffset at op {} in function {:?}", i, f.name(code));
            }
        }
        // Advance scopes and check how many scopes closed
        let (if_else_closed, switches_closed) = state.scopes.advance();

        // Restore register state for each closed If/Else scope
        // Only restore registers that were SET TO NULL inside the scope.
        // This prevents null.array patterns while allowing constructors and
        // other meaningful values to persist after the scope.
        for _ in 0..if_else_closed {
            let set_to_null = state.set_to_null_in_scope.pop().unwrap_or_default();
            if let Some(saved_state) = state.saved_reg_states.pop() {
                for reg in set_to_null {
                    if let Some(original_expr) = saved_state.get(&reg) {
                        // Register was set to null inside scope - restore to original
                        state.reg_state.insert(reg, original_expr.clone());
                    }
                }
            }
        }

        // Pop saved states for closed switch statements
        for _ in 0..switches_closed {
            state.switch_saved_states.pop();
        }
    }
    let mut statements = state.scopes.statements();

    // Reconstruct array literals from alloc_bytes patterns
    post::reconstruct_array_literals(code, &mut statements);

    // AST post processing step !
    // It makes a single pass for all visitors
    post::visit(
        code,
        &mut statements,
        &mut [
            Box::new(post::BoundsCheckSimplify),
            Box::new(post::IfExpressions),
            Box::new(post::SwitchExpressions),
            Box::new(post::StringConcat),
            Box::new(post::Itos),
            Box::new(post::Trace),
        ],
    );

    statements
}

/// Decompile a function out of context
pub fn decompile_function(code: &Bytecode, f: &Function) -> Method {
    Method {
        fun: f.findex,
        static_: true,
        dynamic: false,
        statements: decompile_code(code, f),
    }
}

/// Decompile a class with its static and instance fields and methods.
pub fn decompile_class(code: &Bytecode, obj: &TypeObj) -> Class {
    let static_type = obj.get_static_type(code);

    let mut fields = Vec::new();
    for (i, f) in obj.own_fields.iter().enumerate() {
        if obj
            .bindings
            .contains_key(&RefField(i + obj.fields.len() - obj.own_fields.len()))
        {
            continue;
        }
        fields.push(ClassField {
            name: f.name(code).to_owned(),
            static_: false,
            ty: f.t,
        });
    }
    if let Some(ty) = static_type {
        for (i, f) in ty.own_fields.iter().enumerate() {
            if ty
                .bindings
                .contains_key(&RefField(i + ty.fields.len() - ty.own_fields.len()))
            {
                continue;
            }
            fields.push(ClassField {
                name: f.name(code).to_owned(),
                static_: true,
                ty: f.t,
            });
        }
    }

    let mut methods = Vec::new();
    for fun in obj.bindings.values() {
        // Skip native functions - can't decompile them
        if let Some(func) = fun.as_fn(code) {
            methods.push(Method {
                fun: *fun,
                static_: false,
                dynamic: true,
                statements: decompile_code(code, func),
            })
        }
    }
    if let Some(ty) = static_type {
        for fun in ty.bindings.values() {
            // Skip native functions - can't decompile them
            if let Some(func) = fun.as_fn(code) {
                methods.push(Method {
                    fun: *fun,
                    static_: true,
                    dynamic: false,
                    statements: decompile_code(code, func),
                })
            }
        }
    }
    for f in &obj.protos {
        // Skip native functions - can't decompile them
        if let Some(func) = f.findex.as_fn(code) {
            methods.push(Method {
                fun: f.findex,
                static_: false,
                dynamic: false,
                statements: decompile_code(code, func),
            })
        }
    }

    Class {
        name: obj.name(code).to_owned(),
        parent: obj
            .super_
            .and_then(|ty| ty.as_obj(code))
            .map(|ty| ty.name(code).to_owned()),
        fields,
        methods,
    }
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::hint::black_box;
    use std::io::BufReader;

    use hlbc::Bytecode;

    use crate::{decompile_class, decompile_code, decompile_function};

    #[test]
    fn decomp_code_all() {
        for entry in fs::read_dir("../../data").unwrap() {
            let path = entry.unwrap().path();
            if let Some(ext) = path.extension() {
                if ext == "hl" {
                    let code = Bytecode::from_file(&path).unwrap();
                    for f in &code.functions {
                        black_box(decompile_code(&code, f));
                    }
                }
            }
        }
    }

    #[test]
    fn decomp_fn_all() {
        for entry in fs::read_dir("../../data").unwrap() {
            let path = entry.unwrap().path();
            if let Some(ext) = path.extension() {
                if ext == "hl" {
                    let code = Bytecode::from_file(&path).unwrap();
                    for f in &code.functions {
                        black_box(decompile_function(&code, f));
                    }
                }
            }
        }
    }

    #[test]
    fn decomp_class_all() {
        for entry in fs::read_dir("../../data").unwrap() {
            let path = entry.unwrap().path();
            if let Some(ext) = path.extension() {
                if ext == "hl" {
                    let code = Bytecode::from_file(&path).unwrap();
                    for t in code.types.iter().filter_map(|t| t.get_type_obj()) {
                        black_box(decompile_class(&code, t));
                    }
                }
            }
        }
    }

    #[test]
    fn decomp_northgard() {
        let code = Bytecode::from_file("E:\\Games\\Northgard\\hlboot.dat").unwrap();
        for f in &code.functions {
            black_box(decompile_code(&code, f));
        }
        for t in code.types.iter().filter_map(|t| t.get_type_obj()) {
            black_box(decompile_class(&code, t));
        }
        for f in &code.functions {
            black_box(decompile_function(&code, f));
        }
    }

    #[test]
    fn decomp_wartales() {
        let code = Bytecode::from_file("E:\\Games\\Wartales\\hlboot.dat").unwrap();
        for f in &code.functions {
            black_box(decompile_code(&code, f));
        }
        for t in code.types.iter().filter_map(|t| t.get_type_obj()) {
            black_box(decompile_class(&code, t));
        }
        for f in &code.functions {
            black_box(decompile_function(&code, f));
        }
    }
}
