//! The decompiler used to get haxe sources back from the bytecode definitions.
//! More info on how everything works in the [wiki](https://github.com/Gui-Yom/hlbc/wiki/Decompilation).
//!
//! The decompiler takes bytecode elements as input and outputs [ast] structures that can be displayed.

use std::collections::HashMap;

use ast::*;
use hlbc::opcodes::Opcode;
use hlbc::types::{Function, ObjProto, RefField, RefGlobal, RefString, Reg, Type, TypeObj};
use hlbc::Bytecode;
#[cfg(feature = "alt")]
mod alt;
/// A simple representation for the Haxe source code generated by the decompiler
pub mod ast;
/// Batch decompilation to files
#[cfg(feature = "batch")]
pub mod batch;
/// Functions to render the [ast] to a string
pub mod fmt;
/// Native function name lookup
pub mod natives;
/// Pass 1: CFG construction using petgraph
pub mod lifter;
/// Pass 2: Dominator computation and loop detection
pub mod analyzer;
/// Pass 3: SSA construction (φ-functions and variable versioning)
pub mod ssa;
/// Pass 4: Type propagation through SSA graph
pub mod type_prop;
/// Pass 5: Convert SSA-CFG to structured AST
pub mod structurer;
/// AST post-processing
mod post;
/// Closure pattern detection and analysis
pub mod closure_analysis;
/// Exception region analysis for try/catch structuring
pub mod exception_analysis;

// Re-export ClosureAnalysis for convenience
pub use closure_analysis::ClosureAnalysis;
// Re-export ExceptionAnalysis for convenience
pub use exception_analysis::ExceptionAnalysis;

/// Map from (static_type_global, field_index) -> initialization Expr
/// Used to track static field initializers extracted from the entrypoint function.
pub type StaticInitMap = HashMap<(RefGlobal, RefField), Expr>;

/// Extract static field initializers from the entrypoint function.
///
/// Static fields are initialized in the entrypoint via SetField operations:
/// ```text
/// OInt      r12 = 10           # Load value into register
/// OGetGlobal r19 = G4          # Load static type ($Counter)
/// OSetField r19.F6 = r12       # Set MULTIPLIER field
/// ```
pub fn extract_static_initializers(code: &Bytecode) -> StaticInitMap {
    let mut result = HashMap::new();
    let entrypoint = code.entrypoint();

    // Track register values as we scan opcodes
    let mut reg_values: HashMap<Reg, Expr> = HashMap::new();
    // Track which register holds which global (for static type refs)
    let mut reg_globals: HashMap<Reg, RefGlobal> = HashMap::new();

    for op in entrypoint.ops.iter() {
        match op {
            // Track constant loads
            Opcode::Int { dst, ptr } => {
                reg_values.insert(*dst, Expr::Constant(Constant::Int(*ptr)));
            }
            Opcode::Float { dst, ptr } => {
                reg_values.insert(*dst, Expr::Constant(Constant::Float(*ptr)));
            }
            Opcode::Bool { dst, value } => {
                reg_values.insert(*dst, Expr::Constant(Constant::Bool(*value)));
            }
            Opcode::String { dst, ptr } => {
                reg_values.insert(*dst, Expr::Constant(Constant::String(*ptr)));
            }
            Opcode::Null { dst } => {
                reg_values.insert(*dst, Expr::Constant(Constant::Null));
            }

            // Track GetGlobal - remember which register holds which global
            Opcode::GetGlobal { dst, global } => {
                reg_globals.insert(*dst, *global);
                // Also check if this global is a string constant
                if let Some(expr) = global_to_expr(code, *global) {
                    reg_values.insert(*dst, expr);
                }
            }

            // SetField on a static type global -> record the initialization
            Opcode::SetField { obj, field, src } => {
                if let Some(&global) = reg_globals.get(obj) {
                    // Check if this global is a static type ($ClassName)
                    if is_static_type_global(code, global) {
                        if let Some(value) = reg_values.get(src).cloned() {
                            result.insert((global, *field), value);
                        }
                    }
                }
            }

            _ => {}
        }
    }
    result
}

/// Check if a global holds a static type (name starts with $).
/// Note: GetGlobal opcode uses 0-based global indexing directly into code.globals.
fn is_static_type_global(code: &Bytecode, global: RefGlobal) -> bool {
    if let Some(global_type) = code.globals.get(global.0) {
        match &code[*global_type] {
            Type::Obj(obj) | Type::Struct(obj) => {
                code[obj.name].starts_with('$')
            }
            _ => false,
        }
    } else {
        false
    }
}

/// Convert a global reference to an Expr if it represents a constant value.
/// Note: GetGlobal opcode uses 0-based global indexing directly into code.globals.
fn global_to_expr(code: &Bytecode, global: RefGlobal) -> Option<Expr> {
    // For string globals, look up the constant value
    let global_type = code.globals.get(global.0)?;
    // String type is index 13
    if global_type.0 == 13 {
        let const_idx = code.globals_initializers.get(&global)?;
        let constants = code.constants.as_ref()?;
        let def = constants.get(*const_idx)?;
        let string_idx = *def.fields.first()?;
        return Some(Expr::Constant(Constant::String(RefString(string_idx))));
    }
    None
}


/// Decompile a function to a list of [Statement]s using the multi-pass pipeline.
///
/// Pipeline: Bytecode → Lifter → CFG → Analyzer → SSA Builder → Type Prop → Structurer → AST
pub fn decompile_code(code: &Bytecode, f: &Function) -> Vec<Statement> {
    decompile_code_with_closures(code, f, None)
}

/// Decompile a function with closure analysis context.
///
/// When `closure_analysis` is provided, the decompiler can:
/// - Detect closure-creating functions and suppress internal enum machinery
/// - Identify captured variables and remap them to original names in inner functions
/// - Inline closure bodies at InstanceClosure sites
pub fn decompile_code_with_closures(
    code: &Bytecode,
    f: &Function,
    closure_analysis: Option<&ClosureAnalysis>,
) -> Vec<Statement> {
    use crate::lifter::Cfg;
    use crate::analyzer::CfgAnalysis;
    use crate::ssa::SsaCfg;
    use crate::type_prop::TypePropagator;
    use crate::structurer::Structurer;

    // Pass 1: Build CFG
    let cfg = Cfg::build(f);

    // Pass 2: Analyze for loops and dominators
    let analysis = CfgAnalysis::analyze(&cfg);

    // Pass 3: Build SSA with φ-functions
    let ssa = SsaCfg::build(f, &cfg, &analysis);

    // Pass 4: Type propagation
    let propagator = TypePropagator::new(code, f, &cfg, &ssa);
    let type_info = propagator.propagate();

    // Pass 5: Structure into AST (with optional closure context)
    let mut structurer = Structurer::new_with_closures(
        code, f, &cfg, &analysis, &ssa, &type_info, closure_analysis
    );
    let mut stmts = structurer.structure();

    // Pass 6: Post-processing transformations
    post::reconstruct_array_literals(code, &mut stmts);

    // Pass 7: Iterative optimization loop
    // Multiple passes can enable each other (e.g., inverting empty ifs can expose early return patterns)
    const MAX_OPT_ITERATIONS: usize = 10;
    for _ in 0..MAX_OPT_ITERATIONS {
        let mut changed = false;

        // Invert empty if bodies: if (c) {} else { body } → if (!c) { body }
        if post::invert_empty_ifs(&mut stmts) {
            changed = true;
        }

        // Flatten early returns: if (x) { return; } else { body } → if (x) { return; } body
        if post::flatten_early_returns(&mut stmts) {
            changed = true;
        }

        // Condense if/else returns to ternary expressions
        post::condense_ternary_returns(&mut stmts);

        if !changed {
            break;
        }
    }

    // Pass 8: Inline single-use variables to reduce verbosity
    post::inline_single_use_vars(&mut stmts);

    // Pass 9: Merge forward declarations with first assignments
    post::merge_declarations(&mut stmts);

    // Pass 10: Inline constants that are immediately returned
    post::inline_constant_returns(&mut stmts);

    // Pass 11: Remove unused forward declarations
    post::remove_unused_var_decls(&mut stmts);

    stmts
}

/// Decompile a function out of context, returning a Method.
pub fn decompile_function(code: &Bytecode, f: &Function) -> Method {
    Method {
        fun: f.findex,
        static_: true,
        dynamic: false,
        override_: false,
        statements: decompile_code(code, f),
    }
}

/// Decompile a function with closure analysis, returning a Method.
pub fn decompile_function_with_closures(
    code: &Bytecode,
    f: &Function,
    closure_analysis: Option<&ClosureAnalysis>,
) -> Method {
    Method {
        fun: f.findex,
        static_: true,
        dynamic: false,
        override_: false,
        statements: decompile_code_with_closures(code, f, closure_analysis),
    }
}


/// Decompile a class with its static and instance fields and methods.
pub fn decompile_class(code: &Bytecode, obj: &TypeObj, static_inits: &StaticInitMap) -> Class {
    decompile_class_with_closures(code, obj, static_inits, None)
}

/// Decompile a class with closure analysis context.
pub fn decompile_class_with_closures(
    code: &Bytecode,
    obj: &TypeObj,
    static_inits: &StaticInitMap,
    closure_analysis: Option<&ClosureAnalysis>,
) -> Class {
    let static_type = obj.get_static_type(code);

    let mut fields = Vec::new();
    for (i, f) in obj.own_fields.iter().enumerate() {
        if obj
            .bindings
            .contains_key(&RefField(i + obj.fields.len() - obj.own_fields.len()))
        {
            continue;
        }
        // Skip fields with empty names (interface implementation cache fields)
        // Note: hlbc converts empty strings to "<none>"
        let field_name = f.name(code);
        if field_name.is_empty() || field_name.as_ref() == "<none>" {
            continue;
        }
        fields.push(ClassField {
            name: field_name.to_owned(),
            static_: false,
            ty: f.t,
            initializer: None, // Instance fields don't have initializers from entrypoint
        });
    }
    if let Some(ty) = static_type {
        // Convert from 1-based TypeObj.global to 0-based opcode global indexing
        let static_global = if obj.global.0 > 0 {
            RefGlobal(obj.global.0 - 1)
        } else {
            obj.global
        };

        for (i, f) in ty.own_fields.iter().enumerate() {
            let field_idx = RefField(i + ty.fields.len() - ty.own_fields.len());
            if ty.bindings.contains_key(&field_idx) {
                continue;
            }
            // Skip fields with empty names (interface implementation cache fields)
            // Note: hlbc converts empty strings to "<none>"
            let field_name = f.name(code);
            if field_name.is_empty() || field_name.as_ref() == "<none>" {
                continue;
            }
            // Look up initializer from entrypoint analysis
            let initializer = static_inits.get(&(static_global, field_idx)).cloned();
            fields.push(ClassField {
                name: field_name.to_owned(),
                static_: true,
                ty: f.t,
                initializer,
            });
        }
    }

    // Helper to check if a proto overrides a parent method
    let is_override = |proto: &ObjProto| -> bool {
        if proto.pindex < 0 {
            return false;
        }
        // Check if parent class has a proto with the same pindex
        if let Some(parent_type) = obj.super_ {
            if let Some(parent_obj) = parent_type.as_obj(code) {
                // Search up the inheritance chain
                let mut current = Some(parent_obj);
                while let Some(curr) = current {
                    for parent_proto in &curr.protos {
                        if parent_proto.pindex >= 0 && parent_proto.pindex == proto.pindex {
                            return true;
                        }
                    }
                    current = curr.super_.and_then(|t| t.as_obj(code));
                }
            }
        }
        false
    };

    let mut methods = Vec::new();
    for fun in obj.bindings.values() {
        // Skip native functions - can't decompile them
        if let Some(func) = fun.as_fn(code) {
            methods.push(Method {
                fun: *fun,
                static_: false,
                dynamic: true,
                override_: false, // Bindings don't override
                statements: decompile_code_with_closures(code, func, closure_analysis),
            })
        }
    }
    if let Some(ty) = static_type {
        for fun in ty.bindings.values() {
            // Skip native functions - can't decompile them
            if let Some(func) = fun.as_fn(code) {
                methods.push(Method {
                    fun: *fun,
                    static_: true,
                    dynamic: false,
                    override_: false, // Static methods don't override
                    statements: decompile_code_with_closures(code, func, closure_analysis),
                })
            }
        }
    }
    for proto in &obj.protos {
        // Skip native functions - can't decompile them
        if let Some(func) = proto.findex.as_fn(code) {
            methods.push(Method {
                fun: proto.findex,
                static_: false,
                dynamic: false,
                override_: is_override(proto),
                statements: decompile_code_with_closures(code, func, closure_analysis),
            })
        }
    }

    Class {
        name: obj.name(code).to_owned(),
        parent: obj
            .super_
            .and_then(|ty| ty.as_obj(code))
            .map(|ty| ty.name(code).to_owned()),
        fields,
        methods,
    }
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::hint::black_box;

    use hlbc::Bytecode;

    use crate::{decompile_class, decompile_code, decompile_function, extract_static_initializers};

    #[test]
    fn decomp_code_all() {
        for entry in fs::read_dir("../../data").unwrap() {
            let path = entry.unwrap().path();
            if let Some(ext) = path.extension() {
                if ext == "hl" {
                    let code = Bytecode::from_file(&path).unwrap();
                    for f in &code.functions {
                        black_box(decompile_code(&code, f));
                    }
                }
            }
        }
    }

    #[test]
    fn decomp_fn_all() {
        for entry in fs::read_dir("../../data").unwrap() {
            let path = entry.unwrap().path();
            if let Some(ext) = path.extension() {
                if ext == "hl" {
                    let code = Bytecode::from_file(&path).unwrap();
                    for f in &code.functions {
                        black_box(decompile_function(&code, f));
                    }
                }
            }
        }
    }

    #[test]
    fn decomp_class_all() {
        for entry in fs::read_dir("../../data").unwrap() {
            let path = entry.unwrap().path();
            if let Some(ext) = path.extension() {
                if ext == "hl" {
                    let code = Bytecode::from_file(&path).unwrap();
                    let static_inits = extract_static_initializers(&code);
                    for t in code.types.iter().filter_map(|t| t.get_type_obj()) {
                        black_box(decompile_class(&code, t, &static_inits));
                    }
                }
            }
        }
    }

    #[test]
    #[ignore] // Requires local game files
    fn decomp_northgard() {
        let code = Bytecode::from_file("E:\\Games\\Northgard\\hlboot.dat").unwrap();
        let static_inits = extract_static_initializers(&code);
        for f in &code.functions {
            black_box(decompile_code(&code, f));
        }
        for t in code.types.iter().filter_map(|t| t.get_type_obj()) {
            black_box(decompile_class(&code, t, &static_inits));
        }
        for f in &code.functions {
            black_box(decompile_function(&code, f));
        }
    }

    #[test]
    #[ignore] // Requires local game files
    fn decomp_wartales() {
        let code = Bytecode::from_file("E:\\Games\\Wartales\\hlboot.dat").unwrap();
        let static_inits = extract_static_initializers(&code);
        for f in &code.functions {
            black_box(decompile_code(&code, f));
        }
        for t in code.types.iter().filter_map(|t| t.get_type_obj()) {
            black_box(decompile_class(&code, t, &static_inits));
        }
        for f in &code.functions {
            black_box(decompile_function(&code, f));
        }
    }
}
