//! Auto-generated type path expansions.
//!
//! Generated by scripts/gen_type_mappings.py from Haxe standard library.
//! This maps short type paths (as stored in bytecode) to full module paths.

/// Expand a short type path to its full module path.
///
/// Returns Some(expanded) if the path needs expansion, None otherwise.
///
/// # Examples
/// ```
/// use hlbc_decompiler::type_mappings::expand_module_path;
/// assert_eq!(expand_module_path("haxe.macro.Binop"), Some("haxe.macro.Expr.Binop"));
/// assert_eq!(expand_module_path("String"), None);
/// ```
pub fn expand_module_path(path: &str) -> Option<&'static str> {
    match path {
        "haxe.Constructible" => Some("haxe.Constraints.Constructible"),
        "haxe.EnumValueTools" => Some("haxe.EnumTools.EnumValueTools"),
        "haxe.FlatEnum" => Some("haxe.Constraints.FlatEnum"),
        "haxe.Function" => Some("haxe.Constraints.Function"),
        "haxe.MainEvent" => Some("haxe.MainLoop.MainEvent"),
        "haxe.NotVoid" => Some("haxe.Constraints.NotVoid"),
        "haxe.Symbol" => Some("haxe.NativeStackTrace.Symbol"),
        "haxe.io.BytesDataAbstract" => Some("haxe.io.BytesData.BytesDataAbstract"),
        "haxe.macro.AbstractType" => Some("haxe.macro.Type.AbstractType"),
        "haxe.macro.AnonType" => Some("haxe.macro.Type.AnonType"),
        "haxe.macro.BaseType" => Some("haxe.macro.Type.BaseType"),
        "haxe.macro.Binop" => Some("haxe.macro.Expr.Binop"),
        "haxe.macro.Case" => Some("haxe.macro.Expr.Case"),
        "haxe.macro.Catch" => Some("haxe.macro.Expr.Catch"),
        "haxe.macro.ClassField" => Some("haxe.macro.Type.ClassField"),
        "haxe.macro.ClassType" => Some("haxe.macro.Type.ClassType"),
        "haxe.macro.DefType" => Some("haxe.macro.Type.DefType"),
        "haxe.macro.EnumField" => Some("haxe.macro.Type.EnumField"),
        "haxe.macro.EnumType" => Some("haxe.macro.Type.EnumType"),
        "haxe.macro.ExprOf" => Some("haxe.macro.Expr.ExprOf"),
        "haxe.macro.Field" => Some("haxe.macro.Expr.Field"),
        "haxe.macro.Function" => Some("haxe.macro.Expr.Function"),
        "haxe.macro.FunctionArg" => Some("haxe.macro.Expr.FunctionArg"),
        "haxe.macro.ImportExpr" => Some("haxe.macro.Expr.ImportExpr"),
        "haxe.macro.MetaAccess" => Some("haxe.macro.Type.MetaAccess"),
        "haxe.macro.Metadata" => Some("haxe.macro.Expr.Metadata"),
        "haxe.macro.MetadataEntry" => Some("haxe.macro.Expr.MetadataEntry"),
        "haxe.macro.ObjectField" => Some("haxe.macro.Expr.ObjectField"),
        "haxe.macro.Position" => Some("haxe.macro.Expr.Position"),
        "haxe.macro.Ref" => Some("haxe.macro.Type.Ref"),
        "haxe.macro.TFunc" => Some("haxe.macro.Type.TFunc"),
        "haxe.macro.TVar" => Some("haxe.macro.Type.TVar"),
        "haxe.macro.TypeDefinition" => Some("haxe.macro.Expr.TypeDefinition"),
        "haxe.macro.TypeParamDecl" => Some("haxe.macro.Expr.TypeParamDecl"),
        "haxe.macro.TypeParameter" => Some("haxe.macro.Type.TypeParameter"),
        "haxe.macro.TypePath" => Some("haxe.macro.Expr.TypePath"),
        "haxe.macro.TypedExpr" => Some("haxe.macro.Type.TypedExpr"),
        "haxe.macro.Unop" => Some("haxe.macro.Expr.Unop"),
        "haxe.macro.Var" => Some("haxe.macro.Expr.Var"),
        "haxe.rtti.Abstractdef" => Some("haxe.rtti.CType.Abstractdef"),
        "haxe.rtti.ClassField" => Some("haxe.rtti.CType.ClassField"),
        "haxe.rtti.Classdef" => Some("haxe.rtti.CType.Classdef"),
        "haxe.rtti.EnumField" => Some("haxe.rtti.CType.EnumField"),
        "haxe.rtti.Enumdef" => Some("haxe.rtti.CType.Enumdef"),
        "haxe.rtti.FunctionArgument" => Some("haxe.rtti.CType.FunctionArgument"),
        "haxe.rtti.MetaData" => Some("haxe.rtti.CType.MetaData"),
        "haxe.rtti.Path" => Some("haxe.rtti.CType.Path"),
        "haxe.rtti.PathParams" => Some("haxe.rtti.CType.PathParams"),
        "haxe.rtti.Platforms" => Some("haxe.rtti.CType.Platforms"),
        "haxe.rtti.TypeInfos" => Some("haxe.rtti.CType.TypeInfos"),
        "haxe.rtti.TypeParams" => Some("haxe.rtti.CType.TypeParams"),
        "haxe.rtti.TypeRoot" => Some("haxe.rtti.CType.TypeRoot"),
        "haxe.rtti.Typedef" => Some("haxe.rtti.CType.Typedef"),
        "ValueType" => Some("Type.ValueType"),
        "hl.Class" => Some("hl.BaseType.Class"),
        "hl.CoreEnum" => Some("hl.BaseType.CoreEnum"),
        "hl.CoreType" => Some("hl.BaseType.CoreType"),
        "hl.Enum" => Some("hl.BaseType.Enum"),
        "hl.TypeKind" => Some("hl.Type.TypeKind"),
        "hl.types.ArrayAccess" => Some("hl.types.ArrayBase.ArrayAccess"),
        "hl.types.ArrayDynIterator" => Some("hl.types.ArrayDyn.ArrayDynIterator"),
        "hl.types.ArrayF32" => Some("hl.types.ArrayBytes.ArrayF32"),
        "hl.types.ArrayF64" => Some("hl.types.ArrayBytes.ArrayF64"),
        "hl.types.ArrayI32" => Some("hl.types.ArrayBytes.ArrayI32"),
        "hl.types.ArrayObjIterator" => Some("hl.types.ArrayObj.ArrayObjIterator"),
        "hl.types.ArrayUI16" => Some("hl.types.ArrayBytes.ArrayUI16"),
        "hl.types.BytesIterator" => Some("hl.types.ArrayBytes.BytesIterator"),
        "hl.types.BytesMapData" => Some("hl.types.BytesMap.BytesMapData"),
        "hl.types.IntMapData" => Some("hl.types.IntMap.IntMapData"),
        "hl.types.ObjectMapData" => Some("hl.types.ObjectMap.ObjectMapData"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_expand_macro_types() {
        assert_eq!(expand_module_path("haxe.macro.Binop"), Some("haxe.macro.Expr.Binop"));
        assert_eq!(expand_module_path("haxe.macro.Unop"), Some("haxe.macro.Expr.Unop"));
        assert_eq!(expand_module_path("haxe.macro.ClassType"), Some("haxe.macro.Type.ClassType"));
    }

    #[test]
    fn test_no_expansion_needed() {
        assert_eq!(expand_module_path("String"), None);
        assert_eq!(expand_module_path("Int"), None);
        assert_eq!(expand_module_path("haxe.ds.StringMap"), None);
    }
}
