[package]
name = "hl-analyze"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Analyze HashLink bytecode for native function compatibility"

[dependencies]
hlbc.workspace = true
clap.workspace = true
anyhow.workspace = true
goblin = "0.9"
glob = "0.3"
